// `abuddy facade-report [--update]` — the reviewed report of a pack's facade types (etc/pack-types.api.md).
//
// `abuddy build` bundles a pack's facade into dist/types/pack-types.d.ts, which packs depending on this one
// compile against. This normalises that bundle so the report changes only when the facade does — imports
// first and sorted, declarations in name order, literal unions sorted, no absolute paths — and compares it
// with the committed report. `--update` writes it instead.
//
// A command rather than a repo script, which is what it was: it reads one pack's dist and writes that pack's
// etc, the same shape as `abuddy validate` and `abuddy build`. As a script it could not share code with the
// bundler that produces its subject, and the normalisation it needs ended up in a third package to be
// reachable from both.
// **One pack uses this today.** `abuddy init` scaffolds no `etc/`, so no external pack has a facade-report
// workflow at all, and the only caller is default-setup's `facade:check`/`facade:update`. Two consequences
// worth knowing before touching it. The bundled path is never exercised end to end — `test:packaged-authoring`
// authors an external pack, and that pack has no report to check — so what is tested here is the command run
// from source. And the open question is not a missing test: a pack with dependents publishes a facade the same
// way default-setup does, so either the scaffold or the release preflight should offer this, or the command is
// default-setup's alone and should say so. Adding coverage for a workflow nobody has would settle it by
// accident, which is why it has not been added.

import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import ts from 'typescript';
import { sortLiteralUnions } from '../build/declaration-text';
import { findPackRoot } from '../utils';

/** Names a top-level statement declares, its sort key */
function declaredName(statement: ts.Statement): string {
  if (ts.isVariableStatement(statement)) return statement.declarationList.declarations.map((d) => d.name.getText()).join(',');
  const name = (statement as { name?: ts.Node }).name;
  return name ? name.getText() : '';
}

/** Import names in sorted order: `import { b, a } from 'x'` → `import { a, b } from 'x'` */
function sortImportNames(text: string): string {
  return text.replace(/\{([^}]*)\}/, (_, names: string) => `{ ${names.split(',').map((n) => n.trim()).filter(Boolean).sort().join(', ')} }`);
}

function report(built: string, packDir: string, bundleFile: string, packId: string): string {
  const bundle = sortLiteralUnions(built, bundleFile);
  const file = ts.createSourceFile(bundleFile, bundle, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const chunks = file.statements.map((statement, index) => {
    const text = bundle.slice(statement.getFullStart(), statement.end).trim();
    // Imports, then declarations, then the export list
    const group = ts.isImportDeclaration(statement) ? 0 : ts.isExportDeclaration(statement) && !statement.moduleSpecifier ? 2 : 1;
    const key = ts.isImportDeclaration(statement) ? (statement.moduleSpecifier as ts.StringLiteral).text : declaredName(statement);
    return { group, key, index, text: group === 0 ? sortImportNames(text) : text };
  });
  // Same-name declarations (overloads, merged interfaces) keep their bundle order
  chunks.sort((a, b) => a.group - b.group || (a.key < b.key ? -1 : a.key > b.key ? 1 : a.index - b.index));
  const body = chunks.map((c, i) => `${i > 0 ? (c.group === 0 ? '\n' : '\n\n') : ''}${c.text}`).join('').replaceAll(packDir, '.');
  return [
    `## Facade types report for the "${packId}" pack`,
    '',
    '> Do not edit this file. It is generated from dist/types/pack-types.d.ts (`abuddy build`), the types packs depending on this one compile against. Regenerate with `npm run facade:update`.',
    '',
    '```ts',
    body,
    '```',
    '',
  ].join('\n');
}

export async function facadeReport(args: string[]): Promise<void> {
  const update = args.includes('--update');
  const packDir = findPackRoot(process.cwd());
  const bundleFile = path.join(packDir, 'dist', 'types', 'pack-types.d.ts');
  const reportFile = path.join(packDir, 'etc', 'pack-types.api.md');
  const shown = (file: string) => path.relative(process.cwd(), file) || '.';

  if (!fs.existsSync(bundleFile)) {
    throw new Error(`${shown(bundleFile)} doesn't exist. Run abuddy build in ${shown(packDir)} first.`);
  }
  const { id } = JSON.parse(fs.readFileSync(path.join(packDir, 'abuddy.json'), 'utf-8')) as { id: string };

  const next = report(fs.readFileSync(bundleFile, 'utf-8'), packDir, bundleFile, id);
  const current = fs.existsSync(reportFile) ? fs.readFileSync(reportFile, 'utf-8') : undefined;

  if (current === next) {
    console.log(`${shown(reportFile)} is up to date`);
    return;
  }
  if (update) {
    fs.mkdirSync(path.dirname(reportFile), { recursive: true });
    fs.writeFileSync(reportFile, next);
    console.log(`Updated ${shown(reportFile)}`);
    return;
  }
  // The diff is the useful half of the failure, so it is printed before the throw that sets the exit code
  const built = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'facade-report-')), 'pack-types.api.md');
  fs.writeFileSync(built, next);
  if (current !== undefined) spawnSync('diff', ['-u', reportFile, built], { stdio: 'inherit' });
  throw new Error(`\n${shown(reportFile)} ${current === undefined ? "doesn't exist" : 'differs from the built facade types (diff above)'}. `
    + 'If the facade change is intended, run npm run facade:update and commit the report.');
}
