// Generated by `npm run sdk-modules:update -w @apack/host` from SHARED_INSTANCE_PACKAGES
// (../../build/shared-deps.ts) and each package's exports map. Do not edit.
import * as _apack_ears from '@apack/ears';
import * as _apack_sdk from '@apack/sdk';
import * as _apack_sdk_artifacts from '@apack/sdk/artifacts';
import * as _apack_sdk_blocks from '@apack/sdk/blocks';
import * as _apack_sdk_build from '@apack/sdk/build';
import * as _apack_sdk_content from '@apack/sdk/content';
import * as _apack_sdk_cron from '@apack/sdk/cron';
import * as _apack_sdk_database_console from '@apack/sdk/database-console';
import * as _apack_sdk_designations from '@apack/sdk/designations';
import * as _apack_sdk_env from '@apack/sdk/env';
import * as _apack_sdk_events from '@apack/sdk/events';
import * as _apack_sdk_framework from '@apack/sdk/framework';
import * as _apack_sdk_helpers from '@apack/sdk/helpers';
import * as _apack_sdk_ids from '@apack/sdk/ids';
import * as _apack_sdk_logger from '@apack/sdk/logger';
import * as _apack_sdk_models from '@apack/sdk/models';
import * as _apack_sdk_repositories from '@apack/sdk/repositories';
import * as _apack_sdk_runtime from '@apack/sdk/runtime';
import * as _apack_sdk_services from '@apack/sdk/services';
import * as _apack_sdk_steps from '@apack/sdk/steps';
import * as _apack_sdk_templates from '@apack/sdk/templates';
import * as _apack_sdk_types from '@apack/sdk/types';
import * as _apack_sdk_utils from '@apack/sdk/utils';
import * as _apack_sdk_utils_compare_versions from '@apack/sdk/utils/compare-versions';
import * as _apack_sdk_utils_pure from '@apack/sdk/utils/pure';

/** Every shared-instance export pack runtime code can require, keyed by specifier */
export const SHARED_INSTANCE_MODULES: Readonly<Record<string, unknown>> = {
  '@apack/ears': _apack_ears,
  '@apack/sdk': _apack_sdk,
  '@apack/sdk/artifacts': _apack_sdk_artifacts,
  '@apack/sdk/blocks': _apack_sdk_blocks,
  '@apack/sdk/build': _apack_sdk_build,
  '@apack/sdk/content': _apack_sdk_content,
  '@apack/sdk/cron': _apack_sdk_cron,
  '@apack/sdk/database-console': _apack_sdk_database_console,
  '@apack/sdk/designations': _apack_sdk_designations,
  '@apack/sdk/env': _apack_sdk_env,
  '@apack/sdk/events': _apack_sdk_events,
  '@apack/sdk/framework': _apack_sdk_framework,
  '@apack/sdk/helpers': _apack_sdk_helpers,
  '@apack/sdk/ids': _apack_sdk_ids,
  '@apack/sdk/logger': _apack_sdk_logger,
  '@apack/sdk/models': _apack_sdk_models,
  '@apack/sdk/repositories': _apack_sdk_repositories,
  '@apack/sdk/runtime': _apack_sdk_runtime,
  '@apack/sdk/services': _apack_sdk_services,
  '@apack/sdk/steps': _apack_sdk_steps,
  '@apack/sdk/templates': _apack_sdk_templates,
  '@apack/sdk/types': _apack_sdk_types,
  '@apack/sdk/utils': _apack_sdk_utils,
  '@apack/sdk/utils/compare-versions': _apack_sdk_utils_compare_versions,
  '@apack/sdk/utils/pure': _apack_sdk_utils_pure,
};
