/**
 * The entity types and relation kinds the SDK owns: the EARS engine's own (Relation) and the data
 * models the SDK's compilers, seeders and services are written against (flows, actions and prompts;
 * library documents and collections; notes; settings and secrets). Every pack has them, and no pack
 * declares them. The generator, the manifest schema and the host all read this module.
 *
 * The shapes here are part of the typed EARS contract (packages/abuddy-sdk/TYPED-EARS.md).
 */
import type { BaseEntity, EARS } from './entities.ts';
import type { TNodeEntity } from '../steps/types.ts';

export const SDK_ENTITIES = {
  /** Every link between two entities */
  Relation: 'Relation',
  Flow: 'Flow',
  /** A flow's step or trigger */
  Node: 'Node',
  /** A step's execution record: runtime only, never persisted */
  TNode: 'TNode',
  Action: 'Action',
  Prompt: 'Prompt',
  Document: 'Document',
  Collection: 'Collection',
  Note: 'Note',
  Settings: 'Settings',
  /** A provider API key, kept in the secrets store */
  Secret: 'Secret',
} as const;

export const SDK_REL_KINDS = {
  CONTAINS: 'contains',
  TRANSITIONS_TO: 'transitions_to',
  INSTANCE_OF: 'instance_of',
  /** A TNode's child executions */
  SPAWNED: 'spawned',
  /** The event TNodes a flow's TNode tracks */
  TRACKED: 'tracked',
} as const;

/** The role of the flow that starts when the app boots */
export const ROOT_FLOW_ROLE = 'root_flow';

/** Entity types kept out of persistence */
export const SDK_EXCLUDED_ENTITY_TYPES: readonly string[] = [SDK_ENTITIES.TNode];

/** Entity types routed to the secrets store */
export const SDK_SECRET_ENTITY_TYPES: readonly string[] = [SDK_ENTITIES.Secret];

export interface ActionParameter {
  type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'any';
  description?: string;
  required?: boolean;
  default?: unknown;
  placeholder?: string;
}

export interface TemplateInput {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'any';
  description?: string;
  required?: boolean;
  defaultValue?: unknown;
  commonSources?: string[];
  example?: unknown;
}

/**
 * The fields every Node row has. A pack's step node types extend it (`interface FireNode extends
 * NodeBase`), and `abuddy generate-entries` unions them into the pack's shape for Node.
 */
export interface NodeBase extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Node;
  nodeType: string;
  label: string;
  description?: string;
  color?: string;
  final?: boolean;
}

export interface RelationEntity extends BaseEntity {
  relationDetails: EARS.RelationDetail;
}

export interface FlowEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Flow;
  shortCode: string;
  label: string;
  description?: string;
  flowType: 'workflow' | 'integration';
  createdAt: number;
  sourceHash?: string;
}

export interface ActionEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Action;
  label: string;
  description?: string;
  category?: string;
  input: Record<string, ActionParameter>;
  actionFn: string;
  output?: unknown;
  /** SHA256 hash of DSL source at last seed. Absent on user-created actions. */
  sourceHash?: string;
  /** Auto-generated by createEntityWithDefaults. */
  shortCode?: string;
  createdAt: number;
  updatedAt: number;
  /** Soft-delete marker, written by the repository rather than removing the row. */
  deleted?: boolean;
  /** Epoch ms at which the soft delete happened. */
  deletedAt?: number;
}

export interface PromptEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Prompt;
  label: string;
  description?: string;
  category?: string;
  inputs: Record<string, TemplateInput>;
  /** Stored as a string, evaluated at runtime */
  templateFn: string;
  /** Optional JSON schema for structured output */
  outputSchema?: unknown;
  /** SHA256 hash of DSL source at last seed. Absent on user-created prompts. */
  sourceHash?: string;
  /** Auto-generated by createEntityWithDefaults. */
  shortCode?: string;
  createdAt: number;
  updatedAt: number;
  /** Soft-delete marker, written by the repository rather than removing the row. */
  deleted?: boolean;
  /** Epoch ms at which the soft delete happened. */
  deletedAt?: number;
}

export interface FieldContent {
  type: 'field';
  fields: Array<{ key: string; value: string }>;
}

export interface ListContent {
  type: 'list';
  items: string[];
}

export interface MarkdownContent {
  type: 'markdown';
  text: string;
}

export interface TextContent {
  type: 'text';
  text: string;
}

export interface CodeContent {
  type: 'code';
  text: string;
  language: string;
}

/** A section of a library document's content, as the library compiler parses it from markdown */
export type ContentSection = FieldContent | ListContent | MarkdownContent | TextContent | CodeContent;

export type ContentType = ContentSection['type'];

export type DocumentShortCode = `DOC-${number}`;

export interface DocumentEntity extends BaseEntity {
  _type: typeof SDK_ENTITIES.Document;
  name: string;
  content: ContentSection[];
  shortCode: DocumentShortCode;
  displayOrder?: number;
  /** Free-form tags, stored directly on the document as a string array. */
  tags?: string[];
  /** SHA256 hash of DSL source at last seed. Absent on user-created documents. */
  sourceHash?: string;
}

export interface CollectionEntity extends BaseEntity {
  _type: typeof SDK_ENTITIES.Collection;
  name: string;
  description?: string;
  displayOrder?: number;
  symlinkPath?: string;
  /** SHA256 hash of DSL source at last seed. Absent on user-created collections. */
  sourceHash?: string;
}

export interface NoteEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Note;
  title: string;
  content: string;
  icon: string | null;
  noteType: 'document' | 'tasklist' | 'task';
  completed: boolean;
  hideCompletedChildren: boolean;
  displayOrder: number;
  savedDisplayOrder?: number;
  createdAt: number;
  updatedAt: number;
  lastSeen: number;
  favorite?: boolean;
  /** Auto-generated by createEntityWithDefaults. */
  shortCode?: string;
  /** Auto-generated by createEntityWithDefaults when not supplied. */
  label?: string;
  deleted?: boolean;
  deletedAt?: number;
}

export type SettingsScope = 'general' | 'plugin' | 'internal';

export interface SettingsEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Settings;
  /** e.g. 'internal', 'general.secrets', 'plugin.flows' */
  name: string;
  /** The settings stored under this name; their structure belongs to the pack that owns them */
  data: unknown;
  /** Optional for backward compatibility */
  type?: SettingsScope;
  /** Optional for backward compatibility */
  label?: string;
}

export type SecretProvider = 'google' | 'anthropic' | 'openai' | 'groq' | 'mistral' | 'cohere' | 'custom';

export interface SecretEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Secret;
  provider: SecretProvider;
  /** Plain text for now; encryption is still to be added */
  encryptedValue: string;
  customName?: string;
  createdAt: number;
  updatedAt?: number;
}

/**
 * Shapes of the SDK's entities; every pack's generated PackShapes includes them. A pack that defines
 * steps reads Node rows as its step node types (and its dependencies') instead of NodeBase.
 */
export type SdkEntityShapes = {
  Relation: RelationEntity;
  Flow: FlowEntity;
  Node: NodeBase;
  TNode: TNodeEntity;
  Action: ActionEntity;
  Prompt: PromptEntity;
  Document: DocumentEntity;
  Collection: CollectionEntity;
  Note: NoteEntity;
  Settings: SettingsEntity;
  Secret: SecretEntity;
};

/** The keys of SdkEntityShapes, at runtime */
export const SDK_SHAPED_ENTITIES = [
  SDK_ENTITIES.Relation, SDK_ENTITIES.Flow, SDK_ENTITIES.Node, SDK_ENTITIES.TNode, SDK_ENTITIES.Action, SDK_ENTITIES.Prompt,
  SDK_ENTITIES.Document, SDK_ENTITIES.Collection, SDK_ENTITIES.Note, SDK_ENTITIES.Settings, SDK_ENTITIES.Secret,
] as const;

// Fails to compile when SDK_SHAPED_ENTITIES and SdkEntityShapes list different entities
type SameKeys<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
const shapedEntitiesMatchShapes: SameKeys<(typeof SDK_SHAPED_ENTITIES)[number], keyof SdkEntityShapes> = true;
void shapedEntitiesMatchShapes;
