/**
 * The entity types and relation kinds the SDK owns: the EARS engine's own (Relation) and the flow
 * model the SDK's flow compiler, flow seeders and steps API are written against. Every pack has
 * them, and no pack declares them. The generator, the manifest schema and the host all read this module.
 */
import type { BaseEntity, EARS } from './entities.ts';
import type { ActionParameter, TemplateInput } from '../build/seed-types.ts';
import type { TNodeEntity } from '../steps/types.ts';

export const SDK_ENTITIES = {
  /** Every link between two entities */
  Relation: 'Relation',
  Flow: 'Flow',
  /** A flow's step or trigger */
  Node: 'Node',
  /** A step's execution record: runtime only, never persisted */
  TNode: 'TNode',
  Action: 'Action',
  Prompt: 'Prompt',
} as const;

export const SDK_REL_KINDS = {
  CONTAINS: 'contains',
  TRANSITIONS_TO: 'transitions_to',
  INSTANCE_OF: 'instance_of',
  /** A TNode's child executions */
  SPAWNED: 'spawned',
  /** The event TNodes a flow's TNode tracks */
  TRACKED: 'tracked',
} as const;

/** Entity types kept out of persistence */
export const SDK_EXCLUDED_ENTITY_TYPES: readonly string[] = [SDK_ENTITIES.TNode];

export interface RelationEntity extends BaseEntity {
  relationDetails: EARS.RelationDetail;
}

export interface FlowEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Flow;
  shortCode: string;
  label: string;
  description?: string;
  flowType: 'workflow' | 'integration';
  createdAt: number;
  sourceHash?: string;
}

export interface ActionEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Action;
  label: string;
  description?: string;
  category?: string;
  input: Record<string, ActionParameter>;
  actionFn: string;
  output?: unknown;
  /** SHA256 hash of DSL source at last seed. Absent on user-created actions. */
  sourceHash?: string;
  /** Auto-generated by createEntityWithDefaults. */
  shortCode?: string;
  createdAt: number;
  updatedAt: number;
  /** Soft-delete marker, written by the repository rather than removing the row. */
  deleted?: boolean;
  /** Epoch ms at which the soft delete happened. */
  deletedAt?: number;
}

export interface PromptEntity extends BaseEntity {
  entityType: typeof SDK_ENTITIES.Prompt;
  label: string;
  description?: string;
  category?: string;
  inputs: Record<string, TemplateInput>;
  /** Stored as a string, evaluated at runtime */
  templateFn: string;
  /** Optional JSON schema for structured output */
  outputSchema?: unknown;
  /** SHA256 hash of DSL source at last seed. Absent on user-created prompts. */
  sourceHash?: string;
  /** Auto-generated by createEntityWithDefaults. */
  shortCode?: string;
  createdAt: number;
  updatedAt: number;
  /** Soft-delete marker, written by the repository rather than removing the row. */
  deleted?: boolean;
  /** Epoch ms at which the soft delete happened. */
  deletedAt?: number;
}

/**
 * Shapes of the SDK's entities; every pack's generated PackShapes includes them. Node has none here:
 * its shape is the union of a pack's step node types, generated per pack.
 */
export type SdkEntityShapes = {
  Relation: RelationEntity;
  Flow: FlowEntity;
  TNode: TNodeEntity;
  Action: ActionEntity;
  Prompt: PromptEntity;
};

/** The keys of SdkEntityShapes, at runtime */
export const SDK_SHAPED_ENTITIES = [
  SDK_ENTITIES.Relation, SDK_ENTITIES.Flow, SDK_ENTITIES.TNode, SDK_ENTITIES.Action, SDK_ENTITIES.Prompt,
] as const;

// Fails to compile when SDK_SHAPED_ENTITIES and SdkEntityShapes list different entities
type SameKeys<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
const shapedEntitiesMatchShapes: SameKeys<(typeof SDK_SHAPED_ENTITIES)[number], keyof SdkEntityShapes> = true;
void shapedEntitiesMatchShapes;
