import * as fs from 'node:fs';
import * as path from 'node:path';
import type { PackSnapshot, PackTypeManifest } from '../../build';
import { resolveDep } from './fetch-deps';
import { findPackRoot, readManifest } from '../utils';

async function loadDepSnapshots(root: string, deps: Record<string, string>): Promise<Map<string, PackSnapshot>> {
  const result = new Map<string, PackSnapshot>();
  for (const [depId, depValue] of Object.entries(deps)) {
    const resolved = await resolveDep(root, depId, depValue);
    if (!resolved) {
      console.warn(`  Warning: could not resolve dependency "${depId}" — try "abuddy fetch-deps"`);
      continue;
    }
    result.set(depId, resolved);
  }
  return result;
}

export async function resolveDepTypes(root: string, deps?: Record<string, string>): Promise<Map<string, PackTypeManifest>> {
  const depSnapshots = deps
    ? await loadDepSnapshots(root, deps)
    : new Map<string, PackSnapshot>();

  const depTypes = new Map<string, PackTypeManifest>();
  for (const [id, snap] of depSnapshots) depTypes.set(id, snap.types);

  return depTypes;
}

// ── Types codegen (dependency type aggregation) ──

const EARS_PROVIDED = new Set(['EARS', 'BaseEntity', 'AllEntities']);

function parseExportedTypeNames(content: string): string[] {
  const names: string[] = [];
  for (const m of content.matchAll(/^export\s+type\s+\{([^}]+)\}/gm))
    names.push(...m[1].split(',').map(s => s.trim()).filter(Boolean));
  for (const m of content.matchAll(/^export\s+(?:declare\s+)?(?:type|interface)\s+(\w+)/gm))
    names.push(m[1]);
  return [...new Set(names)];
}

function emitTypes(depSnapshots: Map<string, PackSnapshot>): string {
  const lines: string[] = [
    '// Auto-generated by `abuddy generate` — do not edit.',
    '',
    "export { EARS } from '../__generated__/ears';",
    "export type { BaseEntity } from '../__generated__/ears';",
    '',
  ];

  const seen = new Set<string>();
  const servicesSources: Array<{ depId: string; defKey: string }> = [];

  for (const [depId, snapshot] of depSnapshots) {
    for (const key of Object.keys(snapshot.defs)) {
      const exported = parseExportedTypeNames(snapshot.defs[key]);

      if (exported.includes('Services')) {
        servicesSources.push({ depId, defKey: key });
      }

      const filtered = exported.filter(n =>
        !EARS_PROVIDED.has(n) && !seen.has(n) && n !== 'Services'
      );
      if (filtered.length === 0) continue;
      for (const n of filtered) seen.add(n);
      lines.push(`export type { ${filtered.join(', ')} } from '../deps/${depId}/defs/${key}';`);
    }
  }

  if (servicesSources.length === 1) {
    const s = servicesSources[0];
    lines.push(`export type { Services } from '../deps/${s.depId}/defs/${s.defKey}';`);
  } else if (servicesSources.length > 1) {
    for (let i = 0; i < servicesSources.length; i++) {
      const s = servicesSources[i];
      lines.push(`import type { Services as _S${i} } from '../deps/${s.depId}/defs/${s.defKey}';`);
    }
    const intersection = servicesSources.map((_, i) => `_S${i}`).join(' & ');
    lines.push(`export type Services = ${intersection};`);
  }

  lines.push('');
  lines.push("import type { EARS as _EARS } from '../__generated__/ears';");
  lines.push('export type EntityId = _EARS.EntityId;');
  lines.push('');
  return lines.join('\n');
}

// ── Command ──

export async function generate(_args: string[], packRoot?: string) {
  const root = packRoot ?? findPackRoot(process.cwd());
  const manifest = readManifest(root);

  console.log(`Generating types for: ${manifest.name}`);

  const depSnapshots = manifest.dependencies
    ? await loadDepSnapshots(root, manifest.dependencies)
    : new Map<string, PackSnapshot>();

  const generatedDir = path.join(root, '.abuddy', 'generated');
  fs.mkdirSync(generatedDir, { recursive: true });

  const typesPath = path.join(generatedDir, 'types.ts');
  fs.writeFileSync(typesPath, emitTypes(depSnapshots));

  const depCount = depSnapshots.size;
  console.log(`  Types:     ${path.relative(process.cwd(), typesPath)}${depCount > 0 ? ` (from ${depCount} deps)` : ''}`);
}
