// Generated by `npm run shared-modules:update -w @abuddy/host` from SHARED_INSTANCE_PACKAGES
// (../../build/shared-deps.ts) and each package's exports map. Do not edit.
import * as _abuddy_ears from '@abuddy/ears';
import * as _abuddy_sdk from '@abuddy/sdk';
import * as _abuddy_sdk_artifacts from '@abuddy/sdk/artifacts';
import * as _abuddy_sdk_blocks from '@abuddy/sdk/blocks';
import * as _abuddy_sdk_build from '@abuddy/sdk/build';
import * as _abuddy_sdk_build_source_conditions from '@abuddy/sdk/build/source-conditions';
import * as _abuddy_sdk_cron from '@abuddy/sdk/cron';
import * as _abuddy_sdk_database_console from '@abuddy/sdk/database-console';
import * as _abuddy_sdk_designations from '@abuddy/sdk/designations';
import * as _abuddy_sdk_env from '@abuddy/sdk/env';
import * as _abuddy_sdk_events from '@abuddy/sdk/events';
import * as _abuddy_sdk_framework from '@abuddy/sdk/framework';
import * as _abuddy_sdk_helpers from '@abuddy/sdk/helpers';
import * as _abuddy_sdk_ids from '@abuddy/sdk/ids';
import * as _abuddy_sdk_logger from '@abuddy/sdk/logger';
import * as _abuddy_sdk_models from '@abuddy/sdk/models';
import * as _abuddy_sdk_repositories from '@abuddy/sdk/repositories';
import * as _abuddy_sdk_runtime from '@abuddy/sdk/runtime';
import * as _abuddy_sdk_seed from '@abuddy/sdk/seed';
import * as _abuddy_sdk_services from '@abuddy/sdk/services';
import * as _abuddy_sdk_steps from '@abuddy/sdk/steps';
import * as _abuddy_sdk_templates from '@abuddy/sdk/templates';
import * as _abuddy_sdk_types from '@abuddy/sdk/types';
import * as _abuddy_sdk_utils from '@abuddy/sdk/utils';
import * as _abuddy_sdk_utils_compare_versions from '@abuddy/sdk/utils/compare-versions';
import * as _abuddy_sdk_utils_pure from '@abuddy/sdk/utils/pure';

/** Every shared-instance export pack runtime code can require, keyed by specifier */
export const SHARED_INSTANCE_MODULES: Readonly<Record<string, unknown>> = {
  '@abuddy/ears': _abuddy_ears,
  '@abuddy/sdk': _abuddy_sdk,
  '@abuddy/sdk/artifacts': _abuddy_sdk_artifacts,
  '@abuddy/sdk/blocks': _abuddy_sdk_blocks,
  '@abuddy/sdk/build': _abuddy_sdk_build,
  '@abuddy/sdk/build/source-conditions': _abuddy_sdk_build_source_conditions,
  '@abuddy/sdk/cron': _abuddy_sdk_cron,
  '@abuddy/sdk/database-console': _abuddy_sdk_database_console,
  '@abuddy/sdk/designations': _abuddy_sdk_designations,
  '@abuddy/sdk/env': _abuddy_sdk_env,
  '@abuddy/sdk/events': _abuddy_sdk_events,
  '@abuddy/sdk/framework': _abuddy_sdk_framework,
  '@abuddy/sdk/helpers': _abuddy_sdk_helpers,
  '@abuddy/sdk/ids': _abuddy_sdk_ids,
  '@abuddy/sdk/logger': _abuddy_sdk_logger,
  '@abuddy/sdk/models': _abuddy_sdk_models,
  '@abuddy/sdk/repositories': _abuddy_sdk_repositories,
  '@abuddy/sdk/runtime': _abuddy_sdk_runtime,
  '@abuddy/sdk/seed': _abuddy_sdk_seed,
  '@abuddy/sdk/services': _abuddy_sdk_services,
  '@abuddy/sdk/steps': _abuddy_sdk_steps,
  '@abuddy/sdk/templates': _abuddy_sdk_templates,
  '@abuddy/sdk/types': _abuddy_sdk_types,
  '@abuddy/sdk/utils': _abuddy_sdk_utils,
  '@abuddy/sdk/utils/compare-versions': _abuddy_sdk_utils_compare_versions,
  '@abuddy/sdk/utils/pure': _abuddy_sdk_utils_pure,
};
