import * as fs from 'node:fs';
import * as path from 'node:path';
import type { PackManifest, PackTypeManifest, PackSnapshot } from '@abuddy/sdk/build';
import { resolveDep } from './fetch-deps';

function findPackRoot(from: string): string {
  let dir = from;
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, 'abuddy.json'))) return dir;
    dir = path.dirname(dir);
  }
  throw new Error('No abuddy.json found. Run this command from inside a pack directory.');
}

async function loadDepSnapshots(root: string, deps: Record<string, string>): Promise<Map<string, PackSnapshot>> {
  const result = new Map<string, PackSnapshot>();

  for (const depId of Object.keys(deps)) {
    const resolved = await resolveDep(root, depId);
    if (!resolved) {
      console.warn(`  Warning: could not resolve dependency "${depId}" — try "abuddy fetch-deps"`);
      continue;
    }
    result.set(depId, resolved);
  }

  return result;
}

interface MergedRegistry {
  entities: Map<string, { value: string; source: string }>;
  relKinds: Map<string, { value: string; source: string }>;
}

function mergeRegistries(
  ownId: string,
  manifest: PackManifest,
  depManifests: Map<string, PackTypeManifest>,
): MergedRegistry {
  const entities = new Map<string, { value: string; source: string }>();
  const relKinds = new Map<string, { value: string; source: string }>();
  const errors: string[] = [];

  if (manifest.entities) {
    for (const [key, value] of Object.entries(manifest.entities)) {
      entities.set(key, { value, source: ownId });
    }
  }

  if (manifest.relKinds) {
    for (const [key, value] of Object.entries(manifest.relKinds)) {
      relKinds.set(key, { value, source: ownId });
    }
  }

  for (const [depId, depTypes] of depManifests) {
    for (const [key, value] of Object.entries(depTypes.entities)) {
      const existing = entities.get(key);
      if (existing && existing.source !== depId) {
        errors.push(`Entity "${key}" declared by both "${existing.source}" and "${depId}"`);
        continue;
      }
      entities.set(key, { value, source: depId });
    }

    for (const [key, value] of Object.entries(depTypes.relKinds)) {
      const existing = relKinds.get(key);
      if (existing && existing.source !== depId) {
        errors.push(`RelKind "${key}" declared by both "${existing.source}" and "${depId}"`);
        continue;
      }
      relKinds.set(key, { value, source: depId });
    }
  }

  if (errors.length > 0) {
    throw new Error(`Type conflicts:\n  ${errors.join('\n  ')}`);
  }

  return { entities, relKinds };
}

function emitEARS(ownId: string, registry: MergedRegistry): string {
  const lines: string[] = [
    '// Auto-generated by `abuddy generate` — do not edit.',
    '',
    'export namespace EARS {',
  ];

  // ── Entity ──
  lines.push('  export namespace Entity {');

  const sourceGroups = new Map<string, string[]>();
  for (const [key, { source }] of registry.entities) {
    const group = sourceGroups.get(source) ?? [];
    group.push(key);
    sourceGroups.set(source, group);
  }

  const ownEntities = sourceGroups.get(ownId);
  if (ownEntities) {
    for (const key of ownEntities) {
      const { value } = registry.entities.get(key)!;
      lines.push(`    export const ${key} = '${value}';`);
      lines.push(`    export type ${key} = typeof ${key};`);
    }
    sourceGroups.delete(ownId);
  }

  for (const [depId, keys] of sourceGroups) {
    lines.push(`    // ${depId}`);
    for (const key of keys) {
      const { value } = registry.entities.get(key)!;
      lines.push(`    export const ${key} = '${value}';`);
      lines.push(`    export type ${key} = typeof ${key};`);
    }
  }

  lines.push('  }');

  const entityUnion = [...registry.entities.keys()].map(k => `Entity.${k}`).join(' | ');
  lines.push(`  export type Entity = ${entityUnion || 'string'};`);
  lines.push('');

  // ── EntityId ──
  lines.push("  export type EntityId<E extends string = string> = import('@abuddy/sdk').EARS.EntityId<E>;");
  lines.push('');

  // ── RelKind ──
  lines.push('  export namespace RelKind {');

  const relSourceGroups = new Map<string, string[]>();
  for (const [key, { source }] of registry.relKinds) {
    const group = relSourceGroups.get(source) ?? [];
    group.push(key);
    relSourceGroups.set(source, group);
  }

  const ownRelKinds = relSourceGroups.get(ownId);
  if (ownRelKinds) {
    for (const key of ownRelKinds) {
      const { value } = registry.relKinds.get(key)!;
      lines.push(`    export const ${key} = '${value}';`);
      lines.push(`    export type ${key} = typeof ${key};`);
    }
    relSourceGroups.delete(ownId);
  }

  for (const [depId, keys] of relSourceGroups) {
    lines.push(`    // ${depId}`);
    for (const key of keys) {
      const { value } = registry.relKinds.get(key)!;
      lines.push(`    export const ${key} = '${value}';`);
      lines.push(`    export type ${key} = typeof ${key};`);
    }
  }

  // Custom helper
  lines.push(`    export const Custom = <T extends string>(k: T) => k as T & RelKind;`);
  lines.push('  }');

  const relUnion = [...registry.relKinds.keys()].map(k => `RelKind.${k}`).join(' | ');
  lines.push(`  export type RelKind = ${relUnion ? `${relUnion} | ` : ''}(string & {});`);
  lines.push('');

  // ── SDK infrastructure (runtime values + types) ──
  lines.push('  export namespace RoleKind {');
  lines.push('    export const Custom = <T extends string>(k: T) => k as T & RoleKind;');
  lines.push('  }');
  lines.push("  export type RoleKind = import('@abuddy/sdk').EARS.RoleKind;");
  lines.push('');

  lines.push('  export const AttrKindValues = { Role: \'role\', RelationDetails: \'relationDetails\' } as const;');
  lines.push('  export namespace AttrKind {');
  lines.push("    export const Role = 'role';");
  lines.push('    export type Role = typeof Role;');
  lines.push("    export const RelationDetails = 'relationDetails';");
  lines.push('    export type RelationDetails = typeof RelationDetails;');
  lines.push('    export const Custom = <T extends string>(k: T) => k as T & AttrKind;');
  lines.push('  }');
  lines.push("  export type AttrKind = import('@abuddy/sdk').EARS.AttrKind;");
  lines.push('');

  lines.push("  export type Blueprint = import('@abuddy/sdk').EARS.Blueprint;");
  lines.push("  export type RelationDetail = import('@abuddy/sdk').EARS.RelationDetail;");
  lines.push("  export type AttributePayloads = import('@abuddy/sdk').EARS.AttributePayloads;");
  lines.push("  export type AttributeValue<K extends AttrKind = AttrKind> = import('@abuddy/sdk').EARS.AttributeValue<K>;");
  lines.push("  export type AttributeTypeMap = import('@abuddy/sdk').EARS.AttributeTypeMap;");
  lines.push("  export type AttributeStore = import('@abuddy/sdk').EARS.AttributeStore;");

  lines.push('}');
  lines.push('');

  // ── BaseEntity ──
  lines.push('export interface BaseEntity {');
  lines.push('  id: EARS.EntityId;');
  lines.push('  entityType: EARS.Entity;');
  lines.push('  createdAt: number;');
  lines.push('  updatedAt?: number;');
  lines.push('}');
  lines.push('');

  // ── AllEntities (backward compat) ──
  lines.push('export const AllEntities = EARS.Entity;');
  lines.push('export type AllEntities = EARS.Entity;');
  lines.push('');

  return lines.join('\n');
}

function emitTypes(depSnapshots: Map<string, PackSnapshot>): string | null {
  const lines: string[] = [
    '// Auto-generated by `abuddy generate` — do not edit.',
    '',
    "export { EARS } from './ears';",
    "export type { BaseEntity } from './ears';",
    '',
  ];

  let hasDefs = false;

  for (const [depId, snapshot] of depSnapshots) {
    const defKeys = Object.keys(snapshot.defs);
    if (defKeys.length === 0) continue;
    hasDefs = true;

    const depsPath = `../deps/${depId}/defs`;

    if (snapshot.defs['action-defs']) {
      lines.push(`export type { Services } from '${depsPath}/action-defs';`);
    }

    if (snapshot.defs['default-setup-defs']) {
      lines.push(`export type { ActionParameter, TemplateInput } from '${depsPath}/default-setup-defs';`);
      lines.push(`export type {`);
      lines.push(`  FlowDSL, FlowConfig, Track,`);
      lines.push(`  DSLStepNode, DSLActionNode, DSLLLMNode, DSLSwitchNode, DSLSwitchCondition,`);
      lines.push(`  DSLFireNode, DSLTransformNode, DSLQueryNode, DSLFlowNode,`);
      lines.push(`  DSLCreateNode, DSLUpdateNode, DSLKeepAliveNode,`);
      lines.push(`} from '${depsPath}/default-setup-defs';`);
    }

    if (snapshot.defs['prompt-defs']) {
      lines.push(`export type { PromptService, PromptContext } from '${depsPath}/prompt-defs';`);
    }
  }

  if (!hasDefs) return null;

  lines.push('');
  lines.push("import type { z } from 'zod';");
  lines.push('export type Z = typeof z;');
  lines.push('');
  lines.push("import type { EARS as _EARS } from './ears';");
  lines.push('export type EntityId = _EARS.EntityId;');
  lines.push('');
  lines.push('import type { ActionParameter as _ActionParameter, TemplateInput as _TemplateInput } from ' +
    `'../deps/${[...depSnapshots.keys()].find(id => depSnapshots.get(id)!.defs['default-setup-defs'])}/defs/default-setup-defs';`);
  lines.push('');
  lines.push('export interface ActionMeta {');
  lines.push('  label: string;');
  lines.push('  description?: string;');
  lines.push('  category?: string;');
  lines.push('  input: Record<string, _ActionParameter>;');
  lines.push('  output?: any;');
  lines.push('}');
  lines.push('');
  lines.push('export interface PromptMeta {');
  lines.push('  label: string;');
  lines.push('  description?: string;');
  lines.push('  category?: string;');
  lines.push('  inputs: Record<string, _TemplateInput>;');
  lines.push('  outputSchema?: any;');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

export async function generate(_args: string[], packRoot?: string) {
  const root = packRoot ?? findPackRoot(process.cwd());
  const manifest = JSON.parse(fs.readFileSync(path.join(root, 'abuddy.json'), 'utf-8')) as PackManifest;

  console.log(`Generating types for: ${manifest.name}`);

  const depSnapshots = manifest.dependencies
    ? await loadDepSnapshots(root, manifest.dependencies)
    : new Map<string, PackSnapshot>();

  const depTypeManifests = new Map<string, PackTypeManifest>();
  for (const [id, snap] of depSnapshots) {
    depTypeManifests.set(id, snap.types);
  }

  const registry = mergeRegistries(manifest.id, manifest, depTypeManifests);
  const earsOutput = emitEARS(manifest.id, registry);

  const generatedDir = path.join(root, '.abuddy', 'generated');
  fs.mkdirSync(generatedDir, { recursive: true });

  const earsPath = path.join(generatedDir, 'ears.ts');
  fs.writeFileSync(earsPath, earsOutput);

  const entityCount = registry.entities.size;
  const relKindCount = registry.relKinds.size;
  const depCount = depSnapshots.size;

  console.log(`  Entities:  ${entityCount}${depCount > 0 ? ` (from ${depCount + 1} sources)` : ''}`);
  console.log(`  RelKinds:  ${relKindCount}`);
  console.log(`  Output:    ${path.relative(process.cwd(), earsPath)}`);

  const typesOutput = emitTypes(depSnapshots);
  if (typesOutput) {
    const typesPath = path.join(generatedDir, 'types.ts');
    fs.writeFileSync(typesPath, typesOutput);
    console.log(`  Types:     ${path.relative(process.cwd(), typesPath)}`);
  }
}
