import * as fs from 'node:fs';
import * as path from 'node:path';
import type { PackManifest, PackTypeManifest, PackSnapshot } from '@abuddy/sdk/build';
import { resolveDep } from './fetch-deps';
import { findPackRoot, readManifest } from '../utils';

async function loadDepSnapshots(root: string, deps: Record<string, string>): Promise<Map<string, PackSnapshot>> {
  const result = new Map<string, PackSnapshot>();
  for (const depId of Object.keys(deps)) {
    const resolved = await resolveDep(root, depId);
    if (!resolved) {
      console.warn(`  Warning: could not resolve dependency "${depId}" — try "abuddy fetch-deps"`);
      continue;
    }
    result.set(depId, resolved);
  }
  return result;
}

// ── EARS codegen ──

interface RegistryEntry { value: string; source: string }

function mergeRegistries(
  ownId: string,
  manifest: PackManifest,
  depManifests: Map<string, PackTypeManifest>,
) {
  function merge(own: Record<string, string> | undefined, kind: string) {
    const map = new Map<string, RegistryEntry>();
    const errors: string[] = [];

    if (own) {
      for (const [key, value] of Object.entries(own))
        map.set(key, { value, source: ownId });
    }

    for (const [depId, dep] of depManifests) {
      const depEntries = kind === 'entity' ? dep.entities : dep.relKinds;
      for (const [key, value] of Object.entries(depEntries)) {
        const existing = map.get(key);
        if (existing && existing.source !== depId) {
          errors.push(`${kind} "${key}" declared by both "${existing.source}" and "${depId}"`);
          continue;
        }
        map.set(key, { value, source: depId });
      }
    }

    if (errors.length > 0) throw new Error(`Type conflicts:\n  ${errors.join('\n  ')}`);
    return map;
  }

  return {
    entities: merge(manifest.entities, 'entity'),
    relKinds: merge(manifest.relKinds, 'relKind'),
  };
}

function emitNamespaceMembers(
  ownId: string,
  registry: Map<string, RegistryEntry>,
): string[] {
  const lines: string[] = [];
  const groups = new Map<string, string[]>();
  for (const [key, { source }] of registry) {
    const g = groups.get(source) ?? [];
    g.push(key);
    groups.set(source, g);
  }

  // Own entries first (no comment header)
  const ownKeys = groups.get(ownId);
  if (ownKeys) {
    for (const key of ownKeys) {
      lines.push(`    export const ${key} = '${registry.get(key)!.value}';`);
      lines.push(`    export type ${key} = typeof ${key};`);
    }
    groups.delete(ownId);
  }

  for (const [depId, keys] of groups) {
    lines.push(`    // ${depId}`);
    for (const key of keys) {
      lines.push(`    export const ${key} = '${registry.get(key)!.value}';`);
      lines.push(`    export type ${key} = typeof ${key};`);
    }
  }

  return lines;
}

function emitEARS(ownId: string, registry: ReturnType<typeof mergeRegistries>): string {
  const entityMembers = emitNamespaceMembers(ownId, registry.entities);
  const relKindMembers = emitNamespaceMembers(ownId, registry.relKinds);

  const entityUnion = [...registry.entities.keys()].map(k => `Entity.${k}`).join(' | ') || 'string';
  const relUnion = [...registry.relKinds.keys()].map(k => `RelKind.${k}`).join(' | ');
  const relType = relUnion ? `${relUnion} | (string & {})` : '(string & {})';

  return `// Auto-generated by \`abuddy generate\` — do not edit.

export namespace EARS {
  export namespace Entity {
${entityMembers.join('\n')}
  }
  export type Entity = ${entityUnion};

  export type EntityId<E extends string = string> = import('@abuddy/sdk').EARS.EntityId<E>;

  export namespace RelKind {
${relKindMembers.join('\n')}
    export const Custom = <T extends string>(k: T) => k as T & RelKind;
  }
  export type RelKind = ${relType};

  export namespace RoleKind {
    export const Custom = <T extends string>(k: T) => k as T & RoleKind;
  }
  export type RoleKind = import('@abuddy/sdk').EARS.RoleKind;

  export const AttrKindValues = { Role: 'role', RelationDetails: 'relationDetails' } as const;
  export namespace AttrKind {
    export const Role = 'role';
    export type Role = typeof Role;
    export const RelationDetails = 'relationDetails';
    export type RelationDetails = typeof RelationDetails;
    export const Custom = <T extends string>(k: T) => k as T & AttrKind;
  }
  export type AttrKind = import('@abuddy/sdk').EARS.AttrKind;

  export type Blueprint = import('@abuddy/sdk').EARS.Blueprint;
  export type RelationDetail = import('@abuddy/sdk').EARS.RelationDetail;
  export type AttributePayloads = import('@abuddy/sdk').EARS.AttributePayloads;
  export type AttributeValue<K extends AttrKind = AttrKind> = import('@abuddy/sdk').EARS.AttributeValue<K>;
  export type AttributeTypeMap = import('@abuddy/sdk').EARS.AttributeTypeMap;
  export type AttributeStore = import('@abuddy/sdk').EARS.AttributeStore;
}

export interface BaseEntity {
  id: EARS.EntityId;
  entityType: EARS.Entity;
  createdAt: number;
  updatedAt?: number;
}

export const AllEntities = EARS.Entity;
export type AllEntities = EARS.Entity;
`;
}

// ── Types codegen ──

const EARS_PROVIDED = new Set(['EARS', 'BaseEntity', 'AllEntities']);

// Only extract type exports — value exports (classes, instances, functions) are runtime
// internals that pack devs receive via function parameters, not direct imports.
function parseExportedTypeNames(content: string): string[] {
  const names: string[] = [];
  for (const m of content.matchAll(/^export\s+type\s+\{([^}]+)\}/gm))
    names.push(...m[1].split(',').map(s => s.trim()).filter(Boolean));
  for (const m of content.matchAll(/^export\s+(?:declare\s+)?(?:type|interface)\s+(\w+)/gm))
    names.push(m[1]);
  return [...new Set(names)];
}

function emitTypes(depSnapshots: Map<string, PackSnapshot>): string {
  const lines: string[] = [
    '// Auto-generated by `abuddy generate` — do not edit.',
    '',
    "export { EARS } from './ears';",
    "export type { BaseEntity } from './ears';",
    '',
  ];

  const seen = new Set<string>();

  for (const [depId, snapshot] of depSnapshots) {
    for (const key of Object.keys(snapshot.defs)) {
      const exported = parseExportedTypeNames(snapshot.defs[key]);
      const filtered = exported.filter(n => !EARS_PROVIDED.has(n) && !seen.has(n));
      if (filtered.length === 0) continue;
      for (const n of filtered) seen.add(n);
      lines.push(`export type { ${filtered.join(', ')} } from '../deps/${depId}/defs/${key}';`);
    }
  }

  lines.push('');
  lines.push("import type { EARS as _EARS } from './ears';");
  lines.push('export type EntityId = _EARS.EntityId;');
  lines.push('');
  return lines.join('\n');
}

// ── Command ──

export async function generate(_args: string[], packRoot?: string) {
  const root = packRoot ?? findPackRoot(process.cwd());
  const manifest = readManifest(root);

  console.log(`Generating types for: ${manifest.name}`);

  const depSnapshots = manifest.dependencies
    ? await loadDepSnapshots(root, manifest.dependencies)
    : new Map<string, PackSnapshot>();

  const depTypes = new Map<string, PackTypeManifest>();
  for (const [id, snap] of depSnapshots) depTypes.set(id, snap.types);

  const registry = mergeRegistries(manifest.id, manifest, depTypes);

  const generatedDir = path.join(root, '.abuddy', 'generated');
  fs.mkdirSync(generatedDir, { recursive: true });

  const earsPath = path.join(generatedDir, 'ears.ts');
  fs.writeFileSync(earsPath, emitEARS(manifest.id, registry));

  const depCount = depSnapshots.size;
  console.log(`  Entities:  ${registry.entities.size}${depCount > 0 ? ` (from ${depCount + 1} sources)` : ''}`);
  console.log(`  RelKinds:  ${registry.relKinds.size}`);
  console.log(`  Output:    ${path.relative(process.cwd(), earsPath)}`);

  const typesPath = path.join(generatedDir, 'types.ts');
  fs.writeFileSync(typesPath, emitTypes(depSnapshots));
  console.log(`  Types:     ${path.relative(process.cwd(), typesPath)}`);
}
