import { type BaseEntity, EARS } from '@/__generated__/ears';


export const REFERENCES = EARS.RelKind.Custom('references');

export interface NoteEntity extends BaseEntity {
  entityType: EARS.Entity.Note;
  title: string;
  content: string;
  icon: string | null;
  noteType: 'document' | 'tasklist' | 'task';
  completed: boolean;
  hideCompletedChildren: boolean;
  displayOrder: number;
  savedDisplayOrder?: number;
  createdAt: number;
  updatedAt: number;
  lastSeen: number;
  favorite?: boolean;
  /** Auto-generated by createEntityWithDefaults. */
  shortCode?: string;
  /** Auto-generated by createEntityWithDefaults when not supplied. */
  label?: string;
  /** Hash of the seed source at last seed. Absent on user-created notes. */
  sourceHash?: string;
  deleted?: boolean;
  deletedAt?: number;
}

export interface NoteDTO {
  id: string;
  title: string;
  content: string;
  icon: string | null;
  noteType: 'document' | 'tasklist' | 'task';
  completed: boolean;
  hideCompletedChildren: boolean;
  parentId: string | null;
  displayOrder: number;
  savedDisplayOrder: number | null;
  childCount: number;
  createdAt: number;
  updatedAt: number;
  lastSeen: number;
  favorite: boolean;
  deletedAt?: number;
}

export type OutgoingNotesSearchEvent = { type: 'NOTES_SEARCH_RESULTS'; results: NoteDTO[] }

export interface NotesConnectedData {
  notes: NoteDTO[];
  settings?: NotesSettings;
}

// ── This feature's settings ───────────────────────────────────────────────
// Its own shape, which the app stores without knowing: the app owns the document, each feature its slice.
export interface NotesSettings {
  tasklistPanelPosition: 'left' | 'right'
  showCollapseIcon: boolean
}

export type IncomingNoteEvents =
  | { type: 'CREATE_NOTE'; title: string; content?: string; icon?: string | null; parentId?: string; skipContentSync?: boolean; noteType?: 'document' | 'tasklist' | 'task'; completed?: boolean; displayOrder?: number }
  | { type: 'UPDATE_NOTE'; id: string; title?: string; content?: string; icon?: string | null; completed?: boolean; hideCompletedChildren?: boolean; favorite?: boolean }
  | { type: 'DELETE_NOTE'; id: string }
  | { type: 'SOFT_DELETE_NOTE'; id: string }
  | { type: 'RESTORE_NOTE'; id: string }
  | { type: 'MOVE_NOTE'; ids: string[]; newParentId: string | null }
  | { type: 'REORDER_NOTE'; id: string; newParentId: string | null; newIndex: number }
  | { type: 'VIEW_NOTE'; id: string }
  | { type: 'SEARCH_NOTES'; query: string }
  | { type: 'GET_TRASHED_NOTES' }
  | { type: 'PERMANENTLY_DELETE_NOTE'; id: string }
  | { type: 'EMPTY_TRASH' }
  | { type: 'IMPORT_NOTES'; directory: string }
  | { type: 'EXPORT_NOTES'; directory: string; format: 'markdown' | 'json' };

export type OutgoingNotesEvents =
  | { type: 'NOTES_CONNECTED'; data: NotesConnectedData }
  | { type: 'NOTE_CREATED'; note: NoteDTO }
  | { type: 'NOTE_UPDATED'; note: NoteDTO }
  | { type: 'NOTE_DELETED'; noteId: string }
  | { type: 'NOTE_RESTORED'; note: NoteDTO }
  | { type: 'TRASHED_NOTES'; notes: NoteDTO[] }
  | OutgoingNotesSearchEvent
  | { type: 'NOTES_IMPORTED'; count: number; errors?: string[] }
  | { type: 'NOTES_IMPORT_FAILED'; errors: string[] }
  | { type: 'NOTES_EXPORTED'; filePath: string; itemCount: number }
  | { type: 'NOTES_EXPORT_FAILED'; errors: string[] }
