import { registerHostModule } from '@abuddy/sdk/runtime';
import { initEARSRuntime } from '@abuddy/sdk/ears';
import * as queryMod from '@/core/ears/helpers/query';
import * as txMod from '@/core/ears/helpers/transaction';
import { createEntity } from '@/core/ears/attribute-storage';
import * as repositoryMod from '@/repository';
import * as sharedRepository from '@/core/shared/repository';
import * as queryHelpers from '@/core/shared/repository/query-helpers';
import * as transactionHelpers from '@/core/shared/repository/transaction-helpers';
import * as attributeStorage from '@/core/ears/attribute-storage';
import * as edgeStore from '@/core/ears/helpers/edge-store';
import * as relationIndex from '@/core/ears/relation-index';
import * as earsGraph from '@/core/ears/helpers/graph';
import * as entityUtils from '@/core/ears/helpers/entity-utils';
import * as lmdbQuery from '@/core/persistence/lmdb/query';
import * as hydrateSharded from '@/core/persistence/partitioning/hydrate-sharded';
import * as loggerMod from '@/core/shared/debug/logger';
import * as trpcMod from '@/core/router/trpc';
import * as busEmitter from '@/core/router/bus-emitter';
import * as routerEvents from '@/core/router/events';
import * as pathsMod from '@/core/shared/paths';
import * as mediaMod from '@/core/shared/media';
import * as exportMod from '@/core/shared/export';
import * as resolveCliMod from '@/core/shared/resolve-cli';
import * as randomIdMod from '@/core/shared/random-id';
import * as binaryOperatorMod from '@/core/shared/binary-operator';
import * as changeDetectionMod from '@/core/shared/change-detection';
import * as displayNameMod from '@/core/shared/display-name';
import * as systemErrorsMod from '@/core/shared/system-errors';
import * as seedMod from '@/core/shared/seed';
import * as lifecycleMod from '@/core/shared/lifecycle';
import * as eventEmitterMod from '@/services/event-emitter';
import * as versionMod from '@/version';

initEARSRuntime({ qx: queryMod.qx, tx: txMod.tx, createEntity });

registerHostModule('repository', repositoryMod);
registerHostModule('shared-repository', sharedRepository);
registerHostModule('query-helpers', queryHelpers);
registerHostModule('transaction-helpers', transactionHelpers);
registerHostModule('attribute-storage', attributeStorage);
registerHostModule('edge-store', edgeStore);
registerHostModule('relation-index', relationIndex);
registerHostModule('ears-graph', earsGraph);
registerHostModule('entity-utils', entityUtils);
registerHostModule('ears-query', queryMod);
registerHostModule('lmdb-query', lmdbQuery);
registerHostModule('hydrate-sharded', hydrateSharded);
registerHostModule('logger', loggerMod);
registerHostModule('trpc', trpcMod);
registerHostModule('bus-emitter', busEmitter);
registerHostModule('router-events', routerEvents);
registerHostModule('paths', pathsMod);
registerHostModule('media', mediaMod);
registerHostModule('export', exportMod);
registerHostModule('resolve-cli', resolveCliMod);
registerHostModule('random-id', randomIdMod);
registerHostModule('binary-operator', binaryOperatorMod);
registerHostModule('change-detection', changeDetectionMod);
registerHostModule('display-name', displayNameMod);
registerHostModule('system-errors', systemErrorsMod);
registerHostModule('seed', seedMod);
registerHostModule('lifecycle', lifecycleMod);
registerHostModule('event-emitter', eventEmitterMod);
registerHostModule('version', versionMod);
