// The facade types report of a built-in pack (etc/pack-types.api.md): the declarations `abuddy build`
// bundled into dist/types/pack-types.d.ts, which packs depending on this one compile against. Normalized
// so it changes only with the facade: imports first and sorted, declarations in name order, no
// absolute paths. Without --local, fails when the committed report differs from the built bundle.
//
//   tsx scripts/facade-report.ts packages/default-setup [--local]
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import ts from 'typescript';

const packDir = path.resolve(process.argv[2] ?? '');
const local = process.argv.includes('--local');
const bundleFile = path.join(packDir, 'dist', 'types', 'pack-types.d.ts');
const reportFile = path.join(packDir, 'etc', 'pack-types.api.md');

if (!fs.existsSync(bundleFile)) {
  console.error(`${path.relative(process.cwd(), bundleFile)} doesn't exist. Run abuddy build in ${path.relative(process.cwd(), packDir) || '.'} first.`);
  process.exit(1);
}
const manifest = JSON.parse(fs.readFileSync(path.join(packDir, 'abuddy.json'), 'utf-8')) as { id: string };

/** Names a top-level statement declares, its sort key */
function declaredName(statement: ts.Statement): string {
  if (ts.isVariableStatement(statement)) return statement.declarationList.declarations.map((d) => d.name.getText()).join(',');
  const name = (statement as { name?: ts.Node }).name;
  return name ? name.getText() : '';
}

/** Import names in sorted order: `import { b, a } from 'x'` → `import { a, b } from 'x'` */
function sortImportNames(text: string): string {
  return text.replace(/\{([^}]*)\}/, (_, names: string) => `{ ${names.split(',').map((n) => n.trim()).filter(Boolean).sort().join(', ')} }`);
}

function report(bundle: string): string {
  const file = ts.createSourceFile(bundleFile, bundle, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const chunks = file.statements.map((statement, index) => {
    const text = bundle.slice(statement.getFullStart(), statement.end).trim();
    // Imports, then declarations, then the export list
    const group = ts.isImportDeclaration(statement) ? 0 : ts.isExportDeclaration(statement) && !statement.moduleSpecifier ? 2 : 1;
    const key = ts.isImportDeclaration(statement) ? (statement.moduleSpecifier as ts.StringLiteral).text : declaredName(statement);
    return { group, key, index, text: group === 0 ? sortImportNames(text) : text };
  });
  // Same-name declarations (overloads, merged interfaces) keep their bundle order
  chunks.sort((a, b) => a.group - b.group || (a.key < b.key ? -1 : a.key > b.key ? 1 : a.index - b.index));
  const body = chunks.map((c, i) => `${i > 0 ? (c.group === 0 ? '\n' : '\n\n') : ''}${c.text}`).join('').replaceAll(packDir, '.');
  return [
    `## Facade types report for the "${manifest.id}" pack`,
    '',
    '> Do not edit this file. It is generated from dist/types/pack-types.d.ts (`abuddy build`), the types packs depending on this one compile against. Regenerate with `npm run facade:update`.',
    '',
    '```ts',
    body,
    '```',
    '',
  ].join('\n');
}

const next = report(fs.readFileSync(bundleFile, 'utf-8'));
const current = fs.existsSync(reportFile) ? fs.readFileSync(reportFile, 'utf-8') : undefined;
if (current === next) {
  console.log(`${path.relative(process.cwd(), reportFile)} is up to date`);
} else if (local) {
  fs.mkdirSync(path.dirname(reportFile), { recursive: true });
  fs.writeFileSync(reportFile, next);
  console.log(`Updated ${path.relative(process.cwd(), reportFile)}`);
} else {
  const built = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'facade-report-')), 'pack-types.api.md');
  fs.writeFileSync(built, next);
  if (current !== undefined) spawnSync('diff', ['-u', reportFile, built], { stdio: 'inherit' });
  console.error(`\n${path.relative(process.cwd(), reportFile)} ${current === undefined ? "doesn't exist" : 'differs from the built facade types (diff above)'}. If the facade change is intended, run npm run facade:update and commit the report.`);
  process.exit(1);
}
