import type {BrainSurfaceState} from '../../agentbuddy-ui/brain/brainTypes';

export const brainSurfaceState: BrainSurfaceState = {
  showLeftPanel: true,
  flowTNodeId: 'TNode-Launch-Flow',
  canGoBack: true,
  pulsingEventType: 'release.ready',
  possibleEvents: [
    {id: 'event-release-ready', label: 'Release ready', eventType: 'release.ready', triggerType: 'listener', scope: 'project'},
    {id: 'event-pr-opened', label: 'Pull request opened', eventType: 'git.pr.opened', triggerType: 'listener', scope: 'workspace'},
    {id: 'event-daily-check', label: 'Daily launch check', eventType: 'schedule.daily', triggerType: 'schedule', cronExpression: '0 9 * * 1-5'},
  ],
  traceNodes: [
    {
      id: 'trace-launch',
      label: 'Launch operating plan',
      tNodeType: 'flow',
      stepNodeType: 'flow',
      status: 'active',
      startedAt: '14:22:10',
      children: [
        {id: 'trace-context', label: 'Capture launch context', tNodeType: 'step', stepNodeType: 'action', status: 'completed', startedAt: '14:22:11'},
        {id: 'trace-summary', label: 'Generate launch summary', tNodeType: 'step', stepNodeType: 'llm', status: 'active', startedAt: '14:22:12'},
      ],
    },
    {
      id: 'trace-pr',
      label: 'Pull request opened',
      tNodeType: 'event',
      eventType: 'git.pr.opened',
      status: 'completed',
      startedAt: '14:21:43',
    },
  ],
  graphNodes: [
    {id: 'brain-event', label: 'Release ready', tNodeType: 'event', eventType: 'release.ready', status: 'completed', x: 150, y: 190},
    {id: 'brain-flow', label: 'Launch operating plan', tNodeType: 'flow', stepNodeType: 'flow', status: 'active', x: 330, y: 190},
    {
      id: 'brain-context',
      label: 'Capture launch context',
      tNodeType: 'step',
      stepNodeType: 'action',
      status: 'completed',
      x: 520,
      y: 100,
      nodeAttributes: {threadId: 'launch-thread', notes: 4, branch: 'as/react-launch-film'},
      output: {contextItems: 12, linkedArtifacts: ['launch-plan.md', 'changes.diff']},
      startedAt: '14:22:11',
      duration: '428ms',
    },
    {
      id: 'brain-summary',
      label: 'Generate summary',
      tNodeType: 'step',
      stepNodeType: 'llm',
      status: 'active',
      x: 520,
      y: 280,
      nodeAttributes: {prompt: 'Release summary', model: 'codex'},
      output: {draft: 'Align launch film with real app UI surfaces...'},
      startedAt: '14:22:12',
      duration: '1.8s',
    },
    {id: 'brain-pr', label: 'Publish PR comment', tNodeType: 'step', stepNodeType: 'action', status: 'pending', x: 710, y: 190},
  ],
  graphEdges: [
    {id: 'brain-event-flow', source: 'brain-event', target: 'brain-flow'},
    {id: 'brain-flow-context', source: 'brain-flow', target: 'brain-context'},
    {id: 'brain-flow-summary', source: 'brain-flow', target: 'brain-summary', animated: true},
    {id: 'brain-summary-pr', source: 'brain-summary', target: 'brain-pr'},
  ],
  selectedNodeId: 'brain-summary',
};
