// Generated by dts-bundle-generator v9.5.1
declare const providers: {
	readonly anthropic: any;
	readonly openai: any;
};
type Provider = keyof typeof providers;
type ModelConfig = {
	provider: Provider;
	model: string;
};
declare function streamText(params: {
	model: ModelConfig;
	prompt?: string;
	messages?: CoreMessage[];
	system?: string;
	temperature?: number;
	maxTokens?: number;
}): Promise<any>;
declare function generateText(params: {
	model: ModelConfig;
	prompt?: string;
	messages?: CoreMessage[];
	system?: string;
	temperature?: number;
	maxTokens?: number;
}): Promise<any>;
declare function streamObject<T>(params: {
	model: ModelConfig;
	schema: any;
	prompt?: string;
	messages?: CoreMessage[];
	system?: string;
	temperature?: number;
	maxTokens?: number;
}): Promise<any>;
declare function generateObject<T>(params: {
	model: ModelConfig;
	schema: any;
	prompt?: string;
	messages?: CoreMessage[];
	system?: string;
	temperature?: number;
	maxTokens?: number;
}): Promise<any>;
type Simplify<T> = {
	[K in keyof T]: T[K];
} & {};
/** Extract a union of inferred objects from a readonly tuple of Zod schemas. */
type EventsFromSchemas<S extends readonly z.ZodTypeAny[]> = {
	[K in keyof S]: z.infer<S[K]>;
}[number];
declare namespace EARS {
	export enum Entity {
		Agent = "Agent",
		Brain = "Brain",
		Message = "Message",
		Thread = "Thread",
		Tag = "Tag",
		Relation = "Relation",
		Artifact = "Artifact",
		Flow = "Flow",
		Node = "Node",
		TNode = "TNode",
		Prompt = "Prompt",
		Action = "Action",
		Document = "Document",
		Collection = "Collection",
		SearchIndex = "SearchIndex",
		Terminal = "Terminal",
		Directory = "Directory"
	}
	export type EntityId = `${Entity}-${string}`;
	const RelKindValues: {
		readonly PARENT_OF: "parent_of";
		readonly CONTAINS: "contains";
		readonly REPLIED_TO: "replied_to";
		readonly HAS: "has";
		readonly BLOCKS: "blocks";
		readonly DEPENDS_ON: "depends_on";
		readonly RELATES_TO: "relates_to";
		readonly DUPLICATES: "duplicates";
		readonly EVENT_TRACE: "event_trace";
		readonly TRANSITIONS_TO: "transitions_to";
		readonly EMITS: "emits";
		readonly INSTANCE_OF: "instance_of";
		readonly SPAWNED: "spawned";
		readonly TRACKED: "tracked";
	};
	export const RelKind: {
		readonly Custom: <T extends string>(k: T) => T & RelKind;
		readonly PARENT_OF: "parent_of";
		readonly CONTAINS: "contains";
		readonly REPLIED_TO: "replied_to";
		readonly HAS: "has";
		readonly BLOCKS: "blocks";
		readonly DEPENDS_ON: "depends_on";
		readonly RELATES_TO: "relates_to";
		readonly DUPLICATES: "duplicates";
		readonly EVENT_TRACE: "event_trace";
		readonly TRANSITIONS_TO: "transitions_to";
		readonly EMITS: "emits";
		readonly INSTANCE_OF: "instance_of";
		readonly SPAWNED: "spawned";
		readonly TRACKED: "tracked";
	};
	export type RelKind = typeof RelKindValues[keyof typeof RelKindValues] | (string & {});
	export interface RelationDetail {
		sourceEntity: EntityId;
		targetEntity: EntityId;
		relationType: RelKind;
		info?: AttributeValue;
	}
	const RoleKindValues: {};
	export const RoleKind: {
		readonly Custom: <T extends string>(k: T) => T & RoleKind;
	};
	export type RoleKind = typeof RoleKindValues[keyof typeof RoleKindValues] | (string & {});
	export const AttrKindValues: {
		readonly Role: "role";
		readonly RelationDetails: "relationDetails";
	};
	export const AttrKind: {
		readonly Custom: <T extends string>(k: T) => T & AttrKind;
		readonly Role: "role";
		readonly RelationDetails: "relationDetails";
	};
	export type AttrKind = typeof AttrKindValues[keyof typeof AttrKindValues] | (string & {});
	export interface AttributePayloads {
		[AttrKindValues.Role]: RoleKind;
		[AttrKindValues.RelationDetails]: RelationDetail;
		[key: string]: any;
	}
	export type AttributeValue<K extends AttrKind = AttrKind> = K extends keyof AttributePayloads ? AttributePayloads[K] : any;
	export type AttributeTypeMap = Record<EntityId, AttributeValue[]>;
	export type AttributeType = AttrKind;
	export type AttributeStore = Record<string, AttributeTypeMap>;
	export type Blueprint = {
		entity: EARS.Entity;
		attrs?: Record<string, unknown>;
		roles?: EARS.RoleKind[];
		uniqueRoles?: EARS.RoleKind[];
		rels?: {
			kind: EARS.RelKind;
			target: Blueprint | EARS.EntityId;
			info?: unknown;
		}[];
	};
	export {};
}
interface BaseEntity {
	id: EARS.EntityId;
	entityType: EARS.Entity;
	createdAt: number;
	updatedAt?: number;
}
/** ── Shared aliases ─────────────────────────────────────────────────────── */
type TimestampMs = number;
type EntityStatus = "active" | "paused" | "completed" | "failed";
type TNodeKind = "flow" | "event" | "step";
/** ── Core entities ──────────────────────────────────────────────────────── */
interface TNodeEntity extends BaseEntity {
	entityType: EARS.Entity.TNode;
	tNodeType: TNodeKind;
	label: string;
	status: EntityStatus;
	startedAt: TimestampMs;
	completedAt?: TimestampMs;
	eventType?: string;
	stepNodeType?: string;
	final?: boolean;
	nodeAttributes?: Record<string, unknown>;
	blueprint?: {
		nodeId: EARS.EntityId;
		flowId: EARS.EntityId;
	};
}
interface TrackEntity extends TNodeEntity {
	children: TrackEntity[];
}
interface EventListenerEntity {
	id: EARS.EntityId;
	nodeId: EARS.EntityId;
	eventType: string;
	label: string;
	mode: "entry" | "internal";
}
interface FlowTNodeData {
	flowTNodeId: EARS.EntityId;
	tNodeTree: TrackEntity[];
	possibleEvents: EventListenerEntity[];
}
interface TNodeUpdate {
	tNodeId: EARS.EntityId;
	status: TNodeEntity["status"];
	eventTNodeId?: EARS.EntityId;
}
/** ── Brain runner types ─────────────────────────────────────────────────── */
interface ExecutionEvent {
	type: string;
	data: Record<string, unknown>;
	timestamp?: TimestampMs;
	source?: string;
}
interface StepRun {
	id: string;
	label: string;
	result: unknown;
	timestamp: TimestampMs;
}
interface ExecutionContext {
	event: ExecutionEvent;
	steps: StepRun[];
	lastStep?: Omit<StepRun, "timestamp">;
}
interface SafeLinkOptions {
	/** Additional info to store with the relation */
	info?: unknown;
	/** If true, creates bidirectional edges automatically */
	symmetric?: boolean;
	/** If specified, prevents cycles within this group of relation kinds */
	acyclicGroup?: readonly EARS.RelKind[];
}
declare function tx(typeOrId: EARS.Entity | EARS.EntityId): {
	readonly put: (k: EARS.AttrKind | string, v: unknown, allowMultiple?: boolean) => any;
	readonly add: (k: EARS.AttrKind | string, v: unknown) => any;
	readonly batchPut: (attrs: Record<string, unknown>) => any;
	readonly merge: (k: EARS.AttrKind, v: unknown, i?: number) => any;
	readonly drop: (k: EARS.AttrKind, i?: number) => any;
	readonly dropIf: (k: EARS.AttrKind, c: unknown) => any;
	readonly update: (k: EARS.AttrKind | string, v: unknown) => any;
	readonly updateBatch: (attrs: Record<string, unknown>) => any;
	readonly grant: (r: string) => any;
	readonly revoke: (r: string) => any;
	readonly ensure: (r: string, scope?: readonly EARS.EntityId[]) => any;
	readonly link: (k: EARS.RelKind, t: EARS.EntityId, info?: unknown) => any;
	readonly relPatch: (rel: EARS.EntityId, u: {
		sourceEntity?: EARS.EntityId;
		targetEntity?: EARS.EntityId;
		info?: unknown;
	}) => any;
	readonly unlink: (rel: EARS.EntityId) => any;
	readonly linkOne: (k: EARS.RelKind, t: EARS.EntityId, info?: unknown) => any;
	readonly safeLink: (k: EARS.RelKind, t: EARS.EntityId, options?: SafeLinkOptions) => any;
	readonly patchLink: (k: EARS.RelKind, t: EARS.EntityId, u: {
		newTarget: EARS.EntityId;
		newInfo?: unknown;
	}) => any;
	readonly unlinkIf: (k: EARS.RelKind, t?: EARS.EntityId) => any;
	readonly unlinkWhere: (c?: {
		kind?: EARS.RelKind;
		target?: EARS.EntityId;
	}) => any;
	readonly define: (def: {
		attributes?: Record<string, unknown>;
		links?: [
			EARS.RelKind,
			EARS.EntityId
		] | Array<[
			EARS.RelKind,
			EARS.EntityId
		]>;
		roles?: string | string[];
	}) => any;
	readonly destroy: () => never;
	readonly id: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
};
interface MessageEntity extends BaseEntity {
	entityType: EARS.Entity.Message;
	text: string;
	sender: "user" | "assistant" | "system";
	timestamp: number;
}
interface ThreadEntity extends BaseEntity {
	entityType: EARS.Entity.Thread;
	topic: string;
	instructions: string;
	sideTopics?: string[];
	timestamp: number;
	lastMessageTimestamp?: number;
	shortCode?: string;
	threadType: "work-item" | "project" | "user";
	status: "backlog" | "open" | "in-progress" | "in-review" | "done";
}
interface ArtifactEntity extends BaseEntity {
	entityType: EARS.Entity.Artifact;
	title?: string;
	content: string | any;
	artifactType: "text" | "code" | "image" | "json" | "graph" | "table" | "kanban" | "slack";
}
interface TagEntity extends BaseEntity {
	entityType: EARS.Entity.Tag;
	name: string;
	color?: string;
}
declare const ThreadRelations: readonly [
	"parent_of",
	"blocks",
	"blocked_by",
	"duplicates"
];
type ThreadLinkRelation = typeof ThreadRelations[number];
type ThreadLinkItem = Pick<ThreadEntity, "id" | "shortCode" | "status" | "timestamp" | "topic" | "threadType"> & {
	relation: ThreadLinkRelation;
};
type ThreadTagItem = Omit<TagEntity, "createdAt" | "updatedAt" | "entityType">;
type ThreadEditFields = Simplify<Pick<ThreadEntity, "topic" | "threadType" | "instructions"> & {
	status?: ThreadEntity["status"];
} & ThreadLinkedFields>;
type ThreadLinkedFields = {
	tags?: ThreadTagItem[];
	linkedThreads?: ThreadLinkItem[];
};
type ThreadCreateData = Simplify<ThreadEditFields>;
type ThreadExtended = Simplify<ThreadEntity & ThreadExtendedData>;
type ThreadExtendedData = ThreadLinkedFields & {
	messages?: Partial<MessageEntity>[];
};
type ThreadStartupData = {
	threads: ThreadExtended[];
	availableTags: TagEntity[];
};
interface ActionParameter {
	type: "string" | "number" | "boolean" | "object" | "array" | "any";
	description?: string;
	required?: boolean;
	default?: any;
	placeholder?: string;
}
interface ActionEntity {
	id: EARS.EntityId;
	entityType: EARS.Entity.Action;
	label: string;
	description?: string;
	category?: string;
	input: Record<string, ActionParameter>;
	actionFn: string;
	output?: any;
	createdAt: number;
	updatedAt: number;
}
interface ActionsStartupData {
	actions: ActionEntity[];
	page: number;
	totalPages: number;
	totalCount: number;
}
/**
 * Defines an input parameter that a prompt template expects
 */
interface TemplateInput {
	name: string;
	type: "string" | "number" | "boolean" | "object" | "array" | "any";
	description?: string;
	required?: boolean;
	defaultValue?: any;
	commonSources?: string[];
	example?: any;
}
/**
 * Defines a prompt entity stored in the system
 */
interface PromptEntity extends BaseEntity {
	entityType: EARS.Entity.Prompt;
	label: string;
	description?: string;
	category?: string;
	inputs: Record<string, TemplateInput>;
	templateFn: string;
	outputSchema?: any;
	createdAt: number;
	updatedAt: number;
}
/**
 * Data sent on prompts system startup
 */
interface PromptsStartupData {
	prompts: PromptEntity[];
	page: number;
	totalPages: number;
	totalCount: number;
}
interface FlowEntity extends BaseEntity {
	entityType: EARS.Entity.Flow;
	shortCode: string;
	label: string;
	description?: string;
	flowType: "workflow" | "integration";
	createdAt: number;
}
interface NodeBase extends BaseEntity {
	entityType: EARS.Entity.Node;
	/** discriminator */
	nodeType: NodeKind;
	label: string;
	description?: string;
	color?: string;
	/** When true, completing this node will trigger parent flow completion */
	final?: boolean;
}
interface QueryNode extends NodeBase {
	nodeType: "query";
	prompt: string;
	resultKey?: string;
}
interface CreateNode extends NodeBase {
	nodeType: "create";
	entityTypeTarget: EARS.Entity;
	entityId?: string;
	inferLabel?: boolean;
}
interface UpdateNode extends NodeBase {
	nodeType: "update";
	entityId: string;
	onMissing?: "fail" | "ignore" | "create";
}
interface DecisionNode extends NodeBase {
	nodeType: "decision";
	conditions: Array<{
		expr: string;
		label?: string;
	}>;
	elseLabel?: string;
}
interface FireNode extends NodeBase {
	nodeType: "fire";
	eventType: string;
	payload?: unknown;
	scope?: "local" | "global";
}
interface ListenNode extends NodeBase {
	nodeType: "listen";
	mode: "entry" | "internal";
	eventType: string;
	debounceMs?: number;
	scope?: "local" | "global";
}
interface TransformNode extends NodeBase {
	nodeType: "transform";
	script: string;
	outputType?: "json" | "text" | "custom";
}
interface FlowNode extends NodeBase {
	nodeType: "flow";
	flowRef: string;
	propagateCtx?: boolean;
	fieldMappings?: Array<{
		target: string;
		source: string;
		default?: any;
	}>;
}
interface KeepAliveNode extends NodeBase {
	nodeType: "keep_alive";
}
interface LLMNode extends NodeBase {
	nodeType: "llm";
	prompt?: string;
	promptTemplateId?: string;
	fieldMappings?: Array<{
		target: string;
		source: string;
		default?: any;
	}>;
	model?: string;
	temperature?: number;
	maxTokens?: number;
	systemPrompt?: string;
}
interface ActionNode extends NodeBase {
	nodeType: "action";
	actionId?: string;
	params?: Record<string, any>;
	fieldMappings?: Array<{
		target: string;
		source: string;
		default?: any;
	}>;
}
type NodeEntity = QueryNode | CreateNode | UpdateNode | ActionNode | DecisionNode | FireNode | ListenNode | TransformNode | FlowNode | KeepAliveNode | LLMNode;
/** Literal union of all nodeType strings (keeps Base clean) */
type NodeKind = NodeEntity["nodeType"];
type NodeCreateInput = Partial<NodeEntity> & {
	actionId?: string;
	promptTemplateId?: string;
};
type EdgeEntity = {
	id: EARS.EntityId;
	kind: EARS.RelKind;
	source: EARS.EntityId;
	target: EARS.EntityId;
	info?: {
		[key: string]: any;
	};
};
interface FlowsStartupData {
	selectedFlowId: EARS.EntityId;
	graph: {
		nodes: NodeEntity[];
		edges: EdgeEntity[];
	};
	flows: Partial<FlowEntity>[];
	rootFlow?: Partial<FlowEntity>;
	models: ModelConfig[];
	prompts: PromptEntity[];
	actions: ActionEntity[];
}
interface ModelConfig {
	id: string;
	name: string;
	provider: string;
	description?: string;
	contextWindow: number;
	maxOutput?: number;
	costPer1kInput?: number;
	costPer1kOutput?: number;
	capabilities?: string[];
}
interface FlowExtendedData {
	nodes: NodeEntity[];
	edges: EdgeEntity[];
}
interface DatabaseSchemaInfo {
	entities: Array<{
		type: EARS.Entity;
	}>;
	attributes: Array<{
		kind: string;
	}>;
	relations: Array<{
		kind: EARS.RelKind;
	}>;
}
interface DatabaseStartupData {
	schema: DatabaseSchemaInfo;
}
declare const LogLevel: z.ZodEnum<[
	"debug",
	"info",
	"warn",
	"error"
]>;
type LogLevel = z.infer<typeof LogLevel>;
declare const LogEntry: z.ZodObject<{
	id: z.ZodString;
	timestamp: z.ZodNumber;
	level: z.ZodEnum<[
		"debug",
		"info",
		"warn",
		"error"
	]>;
	message: z.ZodString;
	source: z.ZodOptional<z.ZodString>;
	meta: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
	stack: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
	message: string;
	id: string;
	timestamp: number;
	level: "debug" | "info" | "warn" | "error";
	source?: string | undefined;
	meta?: Record<string, any> | undefined;
	stack?: string | undefined;
}, {
	message: string;
	id: string;
	timestamp: number;
	level: "debug" | "info" | "warn" | "error";
	source?: string | undefined;
	meta?: Record<string, any> | undefined;
	stack?: string | undefined;
}>;
type LogEntry = z.infer<typeof LogEntry>;
type EmbeddingModelId = "minilm-l6-v2" | "bge-small-en" | "bge-small-en-v1.5" | "bge-base-en" | "bge-base-en-v1.5" | "e5-large-multilingual" | "text-embedding-3-small" | "text-embedding-3-large";
type EmbeddingModel = EmbeddingModelId;
type IndexMetric = "cosine" | "dot_product";
interface SegmentRule {
	id: string;
	type: "text" | "list" | "field";
	occurrence: string;
	key?: string;
	indexMode: "combined" | "separate";
}
interface SearchIndexConfig {
	name: string;
	description: string;
	embeddingModel: EmbeddingModel;
	indexMetric: IndexMetric;
	connectors: number;
	excludeAllSubfolders: boolean;
	excludedFolderIds: EARS.EntityId[];
	excludedDocumentIds: EARS.EntityId[];
	enableSectionIndexing: boolean;
	segmentRules: SegmentRule[];
	constructTemplate: string;
}
interface SearchIndex extends SearchIndexConfig {
	id: EARS.EntityId;
	folderId: EARS.EntityId | null;
	documentCount: number;
	vectorDimensions: number;
	createdAt: number;
	updatedAt: number;
}
type DocumentShortCode = `DOC-${number}`;
interface FieldContent {
	type: "field";
	fields: Array<{
		key: string;
		value: string;
	}>;
}
interface ListContent {
	type: "list";
	items: string[];
}
interface TextBlockContent {
	type: "text";
	text: string;
}
type ContentSection = FieldContent | ListContent | TextBlockContent;
interface DocumentDTO {
	id: EARS.EntityId;
	name: string;
	content: ContentSection[];
	shortCode: DocumentShortCode;
	tags: string[];
	collectionId?: EARS.EntityId;
	collectionPath?: string[];
	displayOrder: number;
	createdAt: string;
	updatedAt: string;
}
interface CollectionDTO {
	id: EARS.EntityId;
	name: string;
	description?: string;
	parentId?: EARS.EntityId;
	path: string[];
	documentCount: number;
	childCollections: CollectionDTO[];
	displayOrder: number;
	createdAt: string;
	updatedAt: string;
}
interface FolderItem {
	type: "folder";
	id: EARS.EntityId;
	name: string;
	parentId: EARS.EntityId | null;
	childCount: number;
	size: string;
	kind: "Folder";
	displayOrder: number;
	createdAt: string;
	updatedAt: string;
}
interface DocumentItem {
	type: "document";
	id: EARS.EntityId;
	name: string;
	shortCode: DocumentShortCode;
	parentId: EARS.EntityId | null;
	content: ContentSection[];
	tags: string[];
	size: string;
	kind: "Document";
	displayOrder: number;
	createdAt: string;
	updatedAt: string;
}
type LibraryItem = FolderItem | DocumentItem;
interface FolderContents {
	items: LibraryItem[];
	currentPath: string[];
	currentFolderId: EARS.EntityId | null;
	breadcrumbs: BreadcrumbItem[];
	searchIndices?: any[];
}
interface BreadcrumbItem {
	id: EARS.EntityId | null;
	name: string;
	path: string[];
}
interface FileInfo {
	name: string;
	path: string;
	type: "file" | "directory";
	size?: number;
	modifiedAt?: Date;
	extension?: string;
}
interface DirectoryContent {
	path: string;
	files: FileInfo[];
}
interface FileContent {
	path: string;
	content: string;
	encoding: string;
}
interface CodeSystemError {
	code: "NOT_FOUND" | "PERMISSION_DENIED" | "INVALID_PATH" | "IO_ERROR" | "FILE_TOO_LARGE" | "SEARCH_ERROR";
	message: string;
	path?: string;
}
interface SearchMatch {
	line: number;
	column: number;
	lineText: string;
	matchStart: number;
	matchEnd: number;
}
interface SearchResult {
	path: string;
	matches: SearchMatch[];
	fileSize?: number;
}
interface SearchProgress {
	filesSearched: number;
	totalFiles: number;
	currentFile?: string;
}
interface GitStatusFile {
	path: string;
	status: "modified" | "added" | "deleted" | "renamed" | "untracked" | "copied" | "typechange" | "unmerged";
	staged: boolean;
	originalPath?: string;
	score?: number;
}
interface GitDiff {
	path: string;
	diff: string;
	staged: boolean;
	originalContent?: string;
	modifiedContent?: string;
}
interface FileChangeInfo {
	path: string;
	modifiedAt: Date;
	changeType: "add" | "change" | "unlink";
}
interface TerminalInfo {
	id: EARS.EntityId;
	title: string;
	pid: number;
	shell?: string;
	cwd: string;
	active: boolean;
	cols: number;
	rows: number;
}
interface QuickOpenResult {
	path: string;
	relativePath: string;
	name: string;
	type: "file" | "directory";
	extension?: string;
	score?: number;
}
type AgentThreadData = {
	id?: ThreadEntity["id"];
	shortCode?: ThreadEntity["shortCode"];
	topic: ThreadEntity["topic"];
	instructions: ThreadEntity["instructions"];
	status: ThreadEntity["status"];
	timestamp: ThreadEntity["timestamp"];
	messages: ThreadExtendedData["messages"];
	artifacts: ArtifactEntity[];
};
type RecentThreadRefreshData = {
	currentThread: AgentThreadData | null;
	threads: Partial<ThreadEntity>[];
};
type AgentStartupData = {
	currentThread: AgentThreadData | null;
	threads: Partial<ThreadEntity>[];
	dashboardArtifacts: Partial<ArtifactEntity>[];
	tabs: Tab[];
};
interface Tab {
	id: string;
	label: string;
	artifacts: ArtifactItem[];
	selectedArtifactId?: string;
}
type ArtifactType = "text" | "code" | "review" | "image" | "kanban" | "slack" | "todo";
interface ArtifactItem {
	id: string;
	type: ArtifactType;
	title: string;
	content: any;
	metadata?: {
		createdAt: number;
		updatedAt?: number;
		[key: string]: any;
	};
}
declare const events: {
	readonly incoming: readonly [
		any,
		any,
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any,
		any
	] | readonly [
		any,
		any
	];
	readonly outgoing: {
		type: "AGENT_STARTUP";
		data: AgentStartupData;
		pluginId: "agent";
	} | {
		type: "REFRESH_RECENT_THREADS";
		data: RecentThreadRefreshData;
		pluginId: "agent";
	} | {
		type: "LOAD_CHAT_THREAD";
		data: AgentThreadData;
		pluginId: "agent";
	} | {
		type: "ARTIFACT_ADDED";
		tabId: string;
		artifact: any;
		pluginId: "agent";
	} | {
		type: "THREAD_TAB_REQUESTED";
		threadId: string;
		artifacts: any[];
		pluginId: "agent";
	} | {
		type: "RECEIVE_PLUGIN_DATA";
		data: FlowTNodeData;
		pluginId: "brain";
	} | {
		type: "TNODE_OPENED";
		tNodeId: EARS.EntityId;
		data: FlowTNodeData;
		pluginId: "brain";
	} | {
		type: "TNODE_SPAWNED";
		tNode: TNodeEntity;
		parentId?: EARS.EntityId | undefined;
		eventTNodeId?: EARS.EntityId | undefined;
		flowTNodeId: EARS.EntityId;
		pluginId: "brain";
	} | {
		type: "TNODE_UPDATED";
		data: TNodeUpdate;
		pluginId: "brain";
	} | {
		type: "EVENT_PULSE";
		eventType: string;
		pluginId: "brain";
	} | {
		type: "TNODE_DETAILS";
		tNodeId: EARS.EntityId;
		details: TNodeEntity | null;
		pluginId: "brain";
	} | {
		type: "DEBUG_TOGGLED";
		enabled: boolean;
		pluginId: "brain";
	} | {
		type: "THREAD_STARTUP";
		data: ThreadStartupData;
		pluginId: "threads";
	} | {
		type: "SET_VIEW_DATA";
		id: EARS.EntityId;
		data: ThreadExtendedData;
		pluginId: "threads";
	} | {
		type: "THREAD_CREATED";
		id: EARS.EntityId;
		shortCode: string;
		entityType: EARS.Entity;
		timestamp: number;
		topic?: string | undefined;
		threadType?: ThreadEntity["threadType"] | undefined;
		instructions?: string | undefined;
		status?: ThreadEntity["status"] | undefined;
		pluginId: "threads";
	} | {
		type: "THREAD_STATUS_UPDATED";
		threadId: string;
		status: ThreadEntity["status"];
		pluginId: "threads";
	} | {
		type: "FLOWS_STARTUP";
		data: FlowsStartupData;
		pluginId: "flows";
	} | {
		type: "FLOW_SELECTED";
		flowId: EARS.EntityId;
		data: {
			nodes: any[];
			edges: any[];
		};
		pluginId: "flows";
	} | {
		type: "FLOW_CREATED";
		flow: FlowEntity;
		flowId: EARS.EntityId;
		data: {
			nodes: any[];
			edges: any[];
		};
		pluginId: "flows";
	} | {
		type: "NODE_CREATED";
		tempId: string;
		nodeId: EARS.EntityId;
		node: any;
		pluginId: "flows";
	} | {
		type: "NODE_UPDATED";
		nodeId: EARS.EntityId;
		node: any;
		pluginId: "flows";
	} | {
		type: "NODE_DELETED";
		nodeId: string;
		pluginId: "flows";
	} | {
		type: "EDGE_CREATED";
		sourceId: EARS.EntityId;
		targetId: EARS.EntityId;
		relId: EARS.EntityId;
		pluginId: "flows";
	} | {
		type: "EDGE_DELETED";
		edgeId: string;
		pluginId: "flows";
	} | {
		type: "EDGE_UPDATED";
		oldEdgeId: EARS.EntityId;
		newEdgeId: EARS.EntityId;
		newSource: EARS.EntityId;
		newTarget: EARS.EntityId;
		pluginId: "flows";
	} | {
		type: "DATABASE_REFRESH";
		data: DatabaseStartupData;
		pluginId: "database";
	} | {
		type: "QUERY_RESULT";
		result: any;
		executionTime: number;
		pluginId: "database";
	} | {
		type: "QUERY_ERROR";
		error: string;
		pluginId: "database";
	} | {
		type: "TRANSACTION_RESULT";
		result: any;
		executionTime: number;
		pluginId: "database";
	} | {
		type: "TRANSACTION_ERROR";
		error: string;
		pluginId: "database";
	} | {
		type: "SNAPSHOT_CREATED";
		filename: string;
		pluginId: "database";
	} | {
		type: "SNAPSHOT_ERROR";
		error: string;
		pluginId: "database";
	} | {
		type: "MAGIC_PROMPT_GENERATED";
		query: string;
		pluginId: "database";
	} | {
		type: "TRACE_FLOWS_RESULT";
		flows: TNodeEntity[];
		pluginId: "database";
	} | {
		type: "FLOW_EVENTS_RESULT";
		flowId: string;
		events: TNodeEntity[];
		hasMore: boolean;
		pluginId: "database";
	} | {
		type: "NODE_DETAILS_RESULT";
		nodeId: string;
		details: TNodeEntity | null;
		pluginId: "database";
	} | {
		type: "LOGS_STARTUP";
		logs: LogEntry[];
		pluginId: "logs";
	} | {
		type: "LOGS_UPDATE";
		logs: LogEntry[];
		pluginId: "logs";
	} | {
		type: "LOG_ADDED";
		log: LogEntry;
		pluginId: "logs";
	} | {
		type: "LOGS_CLEARED";
		pluginId: "logs";
	} | {
		type: "PROMPTS_STARTUP";
		data: PromptsStartupData;
		pluginId: "prompts";
	} | {
		type: "PROMPT_SELECTED";
		promptId: EARS.EntityId;
		data: PromptEntity;
		pluginId: "prompts";
	} | {
		type: "PROMPT_CREATED";
		prompt: PromptEntity;
		promptId: EARS.EntityId;
		pluginId: "prompts";
	} | {
		type: "PROMPT_UPDATED";
		prompt: PromptEntity;
		promptId: EARS.EntityId;
		pluginId: "prompts";
	} | {
		type: "PROMPT_DELETED";
		promptId: EARS.EntityId;
		pluginId: "prompts";
	} | {
		type: "PROMPTS_PAGE_LOADED";
		data: {
			prompts: PromptEntity[];
			page: number;
			totalPages: number;
		};
		pluginId: "prompts";
	} | {
		type: "ACTIONS_LISTED";
		data: ActionsStartupData;
		pluginId: "actions";
	} | {
		type: "ACTION_SELECTED";
		actionId: EARS.EntityId;
		data: ActionEntity;
		pluginId: "actions";
	} | {
		type: "ACTION_CREATED";
		action: ActionEntity;
		actionId: EARS.EntityId;
		pluginId: "actions";
	} | {
		type: "ACTION_UPDATED";
		action: ActionEntity;
		actionId: EARS.EntityId;
		pluginId: "actions";
	} | {
		type: "ACTION_DELETED";
		actionId: EARS.EntityId;
		pluginId: "actions";
	} | {
		type: "LIBRARY_STARTUP";
		data: {
			documents: DocumentDTO[];
			collections: CollectionDTO[];
		};
		pluginId: "library";
	} | {
		type: "DOCUMENTS_LOADED";
		data: {
			documents: DocumentDTO[];
		};
		pluginId: "library";
	} | {
		type: "DOCUMENT_CREATED";
		data: {
			document: DocumentDTO;
		};
		pluginId: "library";
	} | {
		type: "DOCUMENT_UPDATED";
		data: {
			document: DocumentDTO;
		};
		pluginId: "library";
	} | {
		type: "DOCUMENT_DELETED";
		data: {
			documentId: string;
		};
		pluginId: "library";
	} | {
		type: "DOCUMENT_LOADED";
		data: {
			document: DocumentDTO;
		};
		pluginId: "library";
	} | {
		type: "COLLECTIONS_LOADED";
		data: {
			collections: CollectionDTO[];
		};
		pluginId: "library";
	} | {
		type: "COLLECTION_CREATED";
		data: {
			collection: CollectionDTO;
		};
		pluginId: "library";
	} | {
		type: "COLLECTION_UPDATED";
		data: {
			collection: CollectionDTO;
		};
		pluginId: "library";
	} | {
		type: "COLLECTION_DELETED";
		data: {
			collectionId: string;
		};
		pluginId: "library";
	} | {
		type: "LIBRARY_ERROR";
		data: {
			error: string;
		};
		pluginId: "library";
	} | {
		type: "FOLDER_CONTENTS_LOADED";
		data: FolderContents;
		pluginId: "library";
	} | {
		type: "NAVIGATION_CHANGED";
		data: {
			folderId: string | null;
			path: string[];
		};
		pluginId: "library";
	} | {
		type: "ITEM_RENAMED";
		data: {
			item: LibraryItem;
		};
		pluginId: "library";
	} | {
		type: "ITEMS_DELETED";
		data: {
			ids: string[];
		};
		pluginId: "library";
	} | {
		type: "ITEMS_MOVED";
		data: {
			ids: string[];
			targetFolderId: string | null;
		};
		pluginId: "library";
	} | {
		type: "ITEMS_REORDERED";
		data: {
			itemIds: string[];
			targetFolderId: string | null;
		};
		pluginId: "library";
	} | {
		type: "SEARCH_INDICES_LOADED";
		data: {
			indices: SearchIndex[];
		};
		pluginId: "library";
	} | {
		type: "SEARCH_INDEX_CREATED";
		data: {
			index: SearchIndex;
		};
		pluginId: "library";
	} | {
		type: "SEARCH_INDEX_UPDATED";
		data: {
			index: SearchIndex;
		};
		pluginId: "library";
	} | {
		type: "SEARCH_INDEX_DELETED";
		data: {
			indexId: string;
		};
		pluginId: "library";
	} | {
		type: "SEARCH_RESULTS";
		data: {
			results: any[];
		};
		pluginId: "library";
	} | {
		type: "INDEXING_PROGRESS";
		data: {
			indexId: string;
			progress: number;
			total: number;
		};
		pluginId: "library";
	} | {
		type: "explorer.FILES_LISTED";
		data: DirectoryContent;
		pluginId: "code";
	} | {
		type: "explorer.FILE_CREATED";
		data: {
			path: string;
		};
		pluginId: "code";
	} | {
		type: "explorer.FILE_DELETED";
		data: {
			path: string;
		};
		pluginId: "code";
	} | {
		type: "explorer.FILE_RENAMED";
		data: {
			oldPath: string;
			newPath: string;
		};
		pluginId: "code";
	} | {
		type: "explorer.DIRECTORY_CREATED";
		data: {
			path: string;
		};
		pluginId: "code";
	} | {
		type: "explorer.FILE_INFO";
		data: FileInfo;
		pluginId: "code";
	} | {
		type: "explorer.FILE_CONTENT";
		data: FileContent;
		pluginId: "code";
	} | {
		type: "explorer.FILE_SAVED";
		data: {
			path: string;
		};
		pluginId: "code";
	} | {
		type: "explorer.CODE_ERROR";
		data: CodeSystemError;
		pluginId: "code";
	} | {
		type: "explorer.CURRENT_DIRECTORY";
		data: {
			path: string;
			rootDirectory: string;
		};
		pluginId: "code";
	} | {
		type: "explorer.FILE_CHANGED_EXTERNALLY";
		data: FileChangeInfo;
		pluginId: "code";
	} | {
		type: "explorer.QUICK_OPEN_RESULTS";
		data: QuickOpenResult[];
		pluginId: "code";
	} | {
		type: "search.RESULT";
		data: SearchResult;
		pluginId: "code";
	} | {
		type: "search.PROGRESS";
		data: SearchProgress;
		pluginId: "code";
	} | {
		type: "search.COMPLETE";
		data: {
			results: SearchResult[];
			totalMatches: number;
		};
		pluginId: "code";
	} | {
		type: "search.ERROR";
		data: {
			message: string;
		};
		pluginId: "code";
	} | {
		type: "commit.STATUS_RECEIVED";
		data: {
			files: GitStatusFile[];
			branch: string;
			hasUpstream: boolean;
			commitsAhead: number;
			commitsBehind: number;
		};
		pluginId: "code";
	} | {
		type: "commit.DIFF_RECEIVED";
		data: GitDiff;
		pluginId: "code";
	} | {
		type: "commit.FILES_STAGED";
		data: {
			paths: string[];
		};
		pluginId: "code";
	} | {
		type: "commit.FILES_UNSTAGED";
		data: {
			paths: string[];
		};
		pluginId: "code";
	} | {
		type: "commit.COMMIT_SUCCESS";
		data: {
			message: string;
		};
		pluginId: "code";
	} | {
		type: "commit.FILE_REVERTED";
		data: {
			path: string;
		};
		pluginId: "code";
	} | {
		type: "commit.ERROR_RECEIVED";
		data: {
			message: string;
		};
		pluginId: "code";
	} | {
		type: "commit.BRANCH_RETRIEVED";
		data: {
			branch: string;
		};
		pluginId: "code";
	} | {
		type: "commit.BRANCHES_RECEIVED";
		data: {
			branches: string[];
		};
		pluginId: "code";
	} | {
		type: "commit.BRANCH_CHECKOUT_SUCCESS";
		data: {
			branchName: string;
		};
		pluginId: "code";
	} | {
		type: "commit.BRANCH_PUSHED";
		data: {
			branchName: string;
		};
		pluginId: "code";
	} | {
		type: "commit.BRANCH_PULLED";
		data: {
			branchName: string;
		};
		pluginId: "code";
	} | {
		type: "pr.BASE_BRANCH_RECEIVED";
		data: {
			branch: string;
		};
		pluginId: "code";
	} | {
		type: "pr.BRANCH_DIFF_RECEIVED";
		data: {
			files: GitStatusFile[];
			baseBranch: string;
		};
		pluginId: "code";
	} | {
		type: "pr.FILE_DIFF_RECEIVED";
		data: GitDiff;
		pluginId: "code";
	} | {
		type: "pr.ERROR";
		message: string;
		pluginId: "code";
	} | {
		type: "pr.STATUS_CHANGED";
		data: {
			timestamp: Date;
		};
		pluginId: "code";
	} | {
		type: "terminal.CREATED";
		data: TerminalInfo;
		pluginId: "code";
	} | {
		type: "terminal.OUTPUT";
		data: {
			terminalId: string;
			data: string;
		};
		pluginId: "code";
	} | {
		type: "terminal.INITIAL_OUTPUT";
		data: {
			terminalId: string;
			data: string;
		};
		pluginId: "code";
	} | {
		type: "terminal.CLOSED";
		data: {
			terminalId: string;
		};
		pluginId: "code";
	} | {
		type: "terminal.ERROR";
		data: {
			message: string;
			terminalId?: string;
		};
		pluginId: "code";
	} | {
		type: "terminal.TERMINALS_LISTED";
		data: TerminalInfo[];
		pluginId: "code";
	} | {
		type: "terminal.TERMINAL_TAB_OPENED";
		data: TerminalInfo;
		pluginId: "code";
	} | {
		type: "codeActions.ACTIONS_LISTED";
		data: {
			actions: ActionEntity[];
			page: number;
			totalPages: number;
			totalCount: number;
		};
		pluginId: "code";
	} | {
		type: "codeActions.ACTION_SELECTED";
		actionId: string;
		data: ActionEntity & {
			actionFnContent?: string;
		};
		pluginId: "code";
	} | {
		type: "codeActions.ACTION_UPDATED";
		action: ActionEntity;
		actionId: string;
		pluginId: "code";
	} | {
		type: "codeActions.CODE_ERROR";
		data: {
			message: string;
		};
		pluginId: "code";
	} | {
		type: "CODE_STARTUP";
		data: {
			terminals: TerminalInfo[];
			rootDirectory: string | null;
			currentDirectory: string | null;
		};
		pluginId: "code";
	};
};
type OutgoingSystemEvents = typeof events.outgoing;
type IncomingSystemEvents = EventsFromSchemas<typeof events.incoming>;
declare function sendToPlugin<T extends OutgoingSystemEvents>(pluginId: string, event: Omit<T, "pluginId">): void;
declare function sendToSystem<T extends IncomingSystemEvents>(systemId: string, event: Omit<T, "systemId">): void;
declare function onOutgoing(callback: (event: OutgoingSystemEvents) => void): () => void;
declare function onIncoming(callback: (event: IncomingSystemEvents) => void): () => void;
declare function prepareEntity<T extends {
	entityType: EARS.Entity;
}>(entityType: EARS.Entity, data: Partial<T>, defaults?: Partial<T>): Omit<T, "id">;
declare function createEntityWithDefaults<T extends {
	entityType: EARS.Entity;
	shortCode?: string;
	label?: string;
}>(entityType: EARS.Entity, data: Partial<T>, prefix?: string): T & {
	id: EARS.EntityId;
};
declare function updateEntity(id: EARS.EntityId, updates: Record<string, any>): void;
declare function createRelation(sourceId: EARS.EntityId, relationType: EARS.RelKind, targetId: EARS.EntityId): void;
declare function removeRelation(sourceId: EARS.EntityId, relationType: EARS.RelKind, targetId?: EARS.EntityId): void;
declare function grantRole(entityId: EARS.EntityId, role: string): void;
declare function revokeRole(entityId: EARS.EntityId, role: string): void;
type MaybeArr<T> = T | readonly T[];
declare const qx: (seed?: EARS.EntityId | EARS.Entity | readonly EARS.Entity[] | readonly EARS.EntityId[]) => {
	readonly ofType: (t: EARS.Entity) => any;
	readonly inIds: (sub: readonly EARS.EntityId[]) => any;
	readonly where: (k: EARS.AttrKind | string, v?: unknown) => any;
	readonly withRole: (r: string) => any;
	readonly relatedTo: (target: EARS.EntityId) => any;
	readonly related: (kind: string, other: EARS.EntityId, asSrc?: boolean) => any;
	readonly linksTo: (relKinds: MaybeArr<string>, tgtType?: MaybeArr<EARS.Entity>, asSrc?: boolean) => any;
	readonly links: <K extends string>(relKinds: K | readonly K[], tgtType?: MaybeArr<EARS.Entity>, asSrc?: boolean) => Array<{
		relation: K;
		id: EARS.EntityId;
	}>;
	readonly edgeIds: (kinds?: string | readonly string[], asSrc?: boolean) => EARS.EntityId[];
	readonly pick: <A extends readonly string[]>(fields: A) => ({
		id: EARS.EntityId;
	} & {
		[K in A[number]]: unknown;
	})[];
	readonly pickOne: (f: readonly string[]) => any;
	readonly pickAll: () => ({
		id: EARS.EntityId;
	} & {
		[x: string]: unknown;
	})[];
	readonly linksPick: <K extends string, A extends readonly string[]>(relKinds: K | readonly K[], fields: A, tgtType?: MaybeArr<EARS.Entity>) => any[];
	readonly orderBy: (field: string, dir?: "asc" | "desc") => any;
	readonly reverse: () => any;
	readonly limit: (n: number) => any;
	readonly page: (size: number, cursor?: string | null) => {
		readonly items: (`Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`)[];
		readonly nextCursor: string | null;
	};
	readonly distinct: (field?: string) => any;
	readonly groupBy: (field: string) => Map<unknown, /*elided*/ any>;
	readonly ids: () => (`Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`)[];
	readonly id: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
	readonly count: () => number;
	readonly first: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
	readonly last: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}` | null;
	readonly exists: () => boolean;
	readonly map: <T>(fn: (i: EARS.EntityId) => T) => T[];
	readonly forEach: (fn: (i: EARS.EntityId) => void) => {
		readonly ofType: (t: EARS.Entity) => any;
		readonly inIds: (sub: readonly EARS.EntityId[]) => any;
		readonly where: (k: EARS.AttrKind | string, v?: unknown) => any;
		readonly withRole: (r: string) => any;
		readonly relatedTo: (target: EARS.EntityId) => any;
		readonly related: (kind: string, other: EARS.EntityId, asSrc?: boolean) => any;
		readonly linksTo: (relKinds: MaybeArr<string>, tgtType?: MaybeArr<EARS.Entity>, asSrc?: boolean) => any;
		readonly links: <K extends string>(relKinds: K | readonly K[], tgtType?: MaybeArr<EARS.Entity>, asSrc?: boolean) => Array<{
			relation: K;
			id: EARS.EntityId;
		}>;
		readonly edgeIds: (kinds?: string | readonly string[], asSrc?: boolean) => EARS.EntityId[];
		readonly pick: <A extends readonly string[]>(fields: A) => ({
			id: EARS.EntityId;
		} & {
			[K in A[number]]: unknown;
		})[];
		readonly pickOne: (f: readonly string[]) => any;
		readonly pickAll: () => ({
			id: EARS.EntityId;
		} & {
			[x: string]: unknown;
		})[];
		readonly linksPick: <K extends string, A extends readonly string[]>(relKinds: K | readonly K[], fields: A, tgtType?: MaybeArr<EARS.Entity>) => any[];
		readonly orderBy: (field: string, dir?: "asc" | "desc") => any;
		readonly reverse: () => any;
		readonly limit: (n: number) => any;
		readonly page: (size: number, cursor?: string | null) => {
			readonly items: (`Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`)[];
			readonly nextCursor: string | null;
		};
		readonly distinct: (field?: string) => any;
		readonly groupBy: (field: string) => Map<unknown, /*elided*/ any>;
		readonly ids: () => (`Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`)[];
		readonly id: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
		readonly count: () => number;
		readonly first: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
		readonly last: () => `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}` | null;
		readonly exists: () => boolean;
		readonly map: <T>(fn: (i: EARS.EntityId) => T) => T[];
		readonly forEach: any;
		readonly reduce: <T>(fn: (a: T, i: EARS.EntityId) => T, init: T) => T;
	};
	readonly reduce: <T>(fn: (a: T, i: EARS.EntityId) => T, init: T) => T;
};
declare function findById<T>(id: EARS.EntityId): T | undefined;
declare function findAll<T>(entityType: EARS.Entity): T[];
declare function findWhere<T>(entityType: EARS.Entity, field: string, value: any): T[];
declare function findFirst<T>(entityType: EARS.Entity, field: string, value: any): T | undefined;
declare function findWithFields<T>(entityType: EARS.Entity, fields: string[]): T[];
declare function findByIdWithFields<T>(id: EARS.EntityId, fields: string[]): T | undefined;
declare function countEntities(entityType: EARS.Entity): number;
declare function exists(id: EARS.EntityId): boolean;
declare function findWithRole<T>(entityType: EARS.Entity, role: string): T[];
declare function findFirstWithRole<T>(entityType: EARS.Entity, role: string): T | undefined;
interface LaunchOptions {
	headless?: boolean;
	viewport?: {
		width: number;
		height: number;
	};
}
declare class BrowserService {
	private browser;
	private context;
	private page;
	private browserType;
	constructor(browserType?: BrowserType);
	launch(options?: LaunchOptions): Promise<void>;
	close(): Promise<void>;
	private getPage;
	goto(url: string): Promise<void>;
	reload(): Promise<void>;
	goBack(): Promise<void>;
	goForward(): Promise<void>;
	click(selector: string): Promise<void>;
	type(selector: string, text: string): Promise<void>;
	press(key: string): Promise<void>;
	selectOption(selector: string, value: string | string[]): Promise<void>;
	getText(selector: string): Promise<string | null>;
	getAttribute(selector: string, attribute: string): Promise<string | null>;
	isVisible(selector: string): Promise<boolean>;
	isEnabled(selector: string): Promise<boolean>;
	waitForSelector(selector: string, timeout?: number): Promise<ElementHandle<Element> | null>;
	waitForTimeout(timeout: number): Promise<void>;
	waitForLoadState(state?: "load" | "domcontentloaded" | "networkidle"): Promise<void>;
	screenshot(path?: string): Promise<Buffer>;
	title(): Promise<string>;
	url(): Promise<string>;
	evaluate<T = any>(fn: () => T): Promise<T>;
	newPage(): Promise<Page>;
	switchToPage(targetPage: Page): Promise<void>;
	closePage(targetPage: Page): Promise<void>;
	setCookies(cookies: Array<{
		name: string;
		value: string;
		domain?: string;
		path?: string;
	}>): Promise<void>;
	getCookies(): Promise<Array<{
		name: string;
		value: string;
		domain: string;
		path: string;
	}>>;
	clearCookies(): Promise<void>;
	setViewport(width: number, height: number): Promise<void>;
	getBrowser(): Browser | null;
	getContext(): BrowserContext | null;
	getCurrentPage(): Page | null;
}
declare function createBrowser(browserType?: BrowserType): BrowserService;
declare class PromptService {
	getByLabel(label: string): Promise<PromptEntity | undefined>;
	/**
	 * Execute a template with prompt context for accessing other prompts
	 * @param templateFn - The template function body
	 * @param templateParams - Parameters to pass to the template
	 */
	executeTemplate(templateFn: string, templateParams: Record<string, any>): string;
	/**
	 * Get and execute a prompt by label
	 * @param label - The prompt label
	 * @param templateParams - Parameters to pass to the template
	 */
	usePrompt(label: string, templateParams: Record<string, any>): Promise<string | undefined>;
}
declare class ActionService {
	getById(id: EARS.EntityId): Promise<ActionEntity | undefined>;
	getByLabel(label: string): Promise<ActionEntity | undefined>;
	getByCategory(category: string): Promise<ActionEntity[]>;
	executeAction(actionFn: string, params?: Record<string, any>): Promise<any>;
	getAndExecute(label: string, params?: Record<string, any>): Promise<any | undefined>;
}
declare class LibraryService {
	getById(id: EARS.EntityId): Promise<DocumentDTO | undefined>;
	getDocByCode(shortCode: string): Promise<DocumentDTO | undefined>;
	getByName(name: string): Promise<DocumentDTO | undefined>;
	getWithinFolder(folderName: string): Promise<DocumentDTO[]>;
}
/**
 * Common repository types for consistent return values and error handling
 */
type RepositoryResult<T> = {
	success: true;
	data: T;
} | {
	success: false;
	error: string;
	code?: string;
};
type OperationResult = RepositoryResult<void>;
interface DirectoryEntity {
	id: EARS.EntityId;
	entityType: EARS.Entity.Directory;
	path: string;
	label?: string;
	lastAccessedAt: number;
	createdAt: number;
	role?: "lastOpened" | "recent";
}
interface TerminalEntity {
	id: EARS.EntityId;
	entityType: EARS.Entity.Terminal;
	title: string;
	pid: number;
	shell: string;
	cwd: string;
	active: boolean;
	cols: number;
	rows: number;
	createdAt: number;
	updatedAt: number;
	closedAt?: number;
}
interface StartupData {
	terminals: TerminalInfo[];
}
declare const services: {
	logger: {
		source?: string;
		log(level: LogLevel, message: string, meta?: Record<string, any>): void;
		debug(message: string, meta?: Record<string, any>): void;
		info(message: string, meta?: Record<string, any>): void;
		warn(message: string, meta?: Record<string, any>): void;
		error(message: string, meta?: Record<string, any>): void;
	};
	llm: typeof llm;
	emitter: typeof emitter;
	database: typeof database;
	prompt: PromptService;
	action: ActionService;
	library: LibraryService;
	browser: typeof browser;
	repository: {
		readonly actionQueries: {
			readonly byId: (id: EARS.EntityId) => ActionEntity | undefined;
			readonly all: () => ActionEntity[];
			readonly byCategory: (category: string) => ActionEntity[];
			readonly paginated: (page?: number, pageSize?: number) => {
				items: ActionEntity[];
				page: number;
				pageSize: number;
				totalCount: number;
				totalPages: number;
			};
			readonly startupData: (page?: number) => {
				actions: ActionEntity[];
				page: number;
				totalPages: number;
				totalCount: number;
			};
		};
		readonly actionCommands: {
			readonly create: (data: {
				label: string;
				description?: string;
				category?: string;
				input?: Record<string, any>;
				actionFn: string;
				output?: any;
			}) => RepositoryResult<ActionEntity>;
			readonly update: (id: EARS.EntityId, updates: {
				label?: string;
				description?: string;
				category?: string;
				input?: Record<string, any>;
				actionFn?: string;
				output?: any;
			}) => OperationResult;
			readonly delete: (id: EARS.EntityId) => OperationResult;
		};
		readonly agentQueries: {
			readonly threadArtifacts: (threadId: EARS.EntityId) => {
				id: `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
				type: unknown;
				title: unknown;
				content: unknown;
			}[];
			readonly threadData: (threadId: EARS.EntityId) => AgentThreadData;
			readonly refreshThreadsData: () => RecentThreadRefreshData;
			readonly startupData: () => AgentStartupData;
		};
		readonly agentCommands: {
			readonly addMessage: (params: {
				threadId: EARS.EntityId;
				text: string;
				sender: "user" | "assistant" | "system";
			}) => RepositoryResult<{
				id: EARS.EntityId;
				threadId: EARS.EntityId;
				text: string;
				sender: string;
				timestamp: number;
			}>;
		};
		readonly brainQueries: {
			readonly rootFlowTNode: () => EARS.EntityId | undefined;
			readonly tNodeById: (id: EARS.EntityId) => TNodeEntity | null;
			readonly flowEventNodes: (flowId: EARS.EntityId) => ListenNode[];
			readonly eventFirstStep: (eventNodeId: EARS.EntityId) => NodeEntity | undefined;
			readonly nextNodeInFlowTrack: (nodeId: EARS.EntityId) => NodeEntity;
			readonly eventTracks: (flowTNodeId: EARS.EntityId) => TrackEntity[];
			readonly possibleEvents: (flowTNodeId: EARS.EntityId) => EventListenerEntity[];
			readonly extendedTNodeData: (tNodeId: EARS.EntityId) => FlowTNodeData;
			readonly rootData: () => FlowTNodeData;
		};
		readonly brainCommands: {
			readonly createEventTNode: (eventNode: ListenNode, flowTNodeId: EARS.EntityId) => TNodeEntity;
			readonly createFlowTNode: (flowStepId: EARS.EntityId, eventTrackId?: EARS.EntityId, executionContext?: ExecutionContext) => {
				flowTNode: TNodeEntity;
				eventNodes: ListenNode[];
			};
			readonly createStepTNode: (stepId: EARS.EntityId, eventTrackId: EARS.EntityId, executionContext?: ExecutionContext) => {
				tNode: TNodeEntity;
				step: NodeEntity;
			};
			readonly createRootFlowTNode: () => {
				rootFlow: FlowEntity;
				rootFlowTNode: TNodeEntity;
				eventNodes: ListenNode[];
				entryNode: ListenNode;
			};
			readonly updateTNodeStatus: (tNodeId: EARS.EntityId, status: TNodeEntity["status"]) => void;
			readonly updateTNodeResult: (tNodeId: EARS.EntityId, result: any) => void;
			readonly updateTNodeAttributes: (tNodeId: EARS.EntityId, attributes: any) => void;
		};
		readonly flowsQueries: {
			readonly rootFlow: () => EARS.EntityId | undefined;
			readonly getNodeActionId: (nodeId: EARS.EntityId) => EARS.EntityId | undefined;
			readonly node: (nodeId: EARS.EntityId) => NodeEntity | undefined;
			readonly flowNodes: (flowId: EARS.EntityId) => NodeEntity[];
			readonly flowEdges: (flowId: EARS.EntityId) => EdgeEntity[];
			readonly extendedData: (flowId: EARS.EntityId, include?: keyof FlowExtendedData | (keyof FlowExtendedData)[]) => FlowExtendedData;
			readonly startupData: () => FlowsStartupData;
		};
		readonly flowsCommands: {
			readonly createFlow: (flow?: Partial<FlowEntity>) => RepositoryResult<FlowEntity>;
			readonly createFlowWithEntryNode: (flow?: Partial<FlowEntity>) => RepositoryResult<{
				flow: FlowEntity;
				entryNode: NodeEntity;
			}>;
			readonly createNode: (flowId: EARS.EntityId, nodeData: NodeCreateInput) => RepositoryResult<NodeEntity>;
			readonly createEdge: (sourceId: EARS.EntityId, targetId: EARS.EntityId) => RepositoryResult<{
				relId: EARS.EntityId;
			}>;
			readonly updateFlowLabel: (flowId: EARS.EntityId, label: string) => OperationResult;
			readonly updateNode: (nodeId: EARS.EntityId, updates: NodeCreateInput) => OperationResult;
			readonly deleteNode: (nodeId: EARS.EntityId) => OperationResult;
			readonly deleteEdge: (edgeId: EARS.EntityId) => OperationResult;
			readonly updateEdge: (edgeId: EARS.EntityId, oldSource: EARS.EntityId, oldTarget: EARS.EntityId, newSource: EARS.EntityId, newTarget: EARS.EntityId) => RepositoryResult<{
				newRelId: EARS.EntityId;
			}>;
		};
		readonly libraryQueries: {
			readonly getDocuments: (collectionId?: string) => DocumentDTO[];
			readonly getDocument: (id: EARS.EntityId) => DocumentDTO | null;
			readonly getDocumentByShortCode: (shortCode: DocumentShortCode) => DocumentDTO | null;
			readonly getCollections: () => CollectionDTO[];
			readonly getFolderContents: (folderId: EARS.EntityId | null) => FolderContents;
			readonly getFolderPath: (folderId: EARS.EntityId | null) => BreadcrumbItem[];
			readonly getParentFolderId: (folderId: EARS.EntityId) => EARS.EntityId | null;
			readonly getCollectionByName: (name: string) => CollectionDTO | null;
			readonly getDocumentsInCollection: (collectionId: EARS.EntityId) => DocumentDTO[];
		};
		readonly libraryCommands: {
			readonly createDocument: (name: string, content: ContentSection[], tags: string[], collectionId?: EARS.EntityId) => DocumentDTO;
			readonly updateDocument: (id: EARS.EntityId, name: string, content: ContentSection[], tags: string[], collectionId?: EARS.EntityId) => DocumentDTO;
			readonly deleteDocument: (id: EARS.EntityId) => void;
			readonly createCollection: (name: string, description?: string, parentId?: EARS.EntityId) => CollectionDTO;
			readonly updateCollection: (id: EARS.EntityId, name: string, description?: string) => CollectionDTO;
			readonly deleteCollection: (id: EARS.EntityId) => void;
			readonly moveDocument: (documentId: EARS.EntityId, newCollectionId?: EARS.EntityId) => DocumentDTO;
			readonly renameItem: (id: EARS.EntityId, name: string, type: "document" | "folder") => LibraryItem;
			readonly deleteItems: (ids: EARS.EntityId[]) => void;
			readonly moveItems: (ids: EARS.EntityId[], targetFolderId: EARS.EntityId | null) => void;
			readonly reorderItems: (itemIds: EARS.EntityId[], targetIndex: number, targetFolderId: EARS.EntityId | null) => void;
			readonly migrateDocumentShortCodes: () => void;
			readonly migrateDisplayOrders: () => void;
		};
		readonly promptQueries: {
			byId: (id: EARS.EntityId) => PromptEntity | undefined;
			all: () => PromptEntity[];
			byLabel: (label: string) => PromptEntity | undefined;
			startupData: (page?: number, pageSize?: number) => {
				prompts: PromptEntity[];
				page: number;
				totalPages: number;
				totalCount: number;
			};
		};
		readonly promptCommands: {
			create: (input: {
				label: string;
				description?: string;
				templateFn: string;
				inputs?: Record<string, any>;
			}) => RepositoryResult<PromptEntity>;
			update: (id: EARS.EntityId, updates: {
				label?: string;
				description?: string;
				templateFn?: string;
				inputs?: Record<string, any>;
			}) => OperationResult;
			delete: (id: EARS.EntityId) => OperationResult;
		};
		readonly terminalQueries: {
			byId: (id: EARS.EntityId) => TerminalEntity | undefined;
			all: () => TerminalEntity[];
			active: () => TerminalEntity[];
			getStartupData: () => StartupData;
		};
		readonly terminalCommands: {
			create: (terminalInfo: Partial<TerminalInfo> & {
				id: EARS.EntityId;
			}) => EARS.EntityId;
			resize: (id: EARS.EntityId, cols: number, rows: number) => void;
			updatePid: (id: EARS.EntityId, pid: number) => void;
			markClosed: (id: EARS.EntityId) => void;
			delete: (id: EARS.EntityId) => void;
		};
		readonly directoryQueries: {
			getLastOpenedDirectory: () => DirectoryEntity | undefined;
			getRecentDirectories: (limit?: number) => DirectoryEntity[];
			findByPath: (path: string) => DirectoryEntity | undefined;
		};
		readonly directoryCommands: {
			saveDirectory: (path: string, label?: string) => EARS.EntityId;
			markAsLastOpened: (path: string) => void;
			clearAll: () => void;
		};
		readonly threadQueries: {
			readonly byId: (id: EARS.EntityId) => ThreadEntity | undefined;
			readonly all: () => ThreadEntity[];
			readonly allByRecency: () => ThreadEntity[];
			readonly messages: (threadId: EARS.EntityId) => Partial<MessageEntity>[];
			readonly tags: (threadId: EARS.EntityId) => ThreadTagItem[];
			readonly linkedThreads: (threadId: EARS.EntityId) => any[];
			readonly extendedData: (threadId: EARS.EntityId, include?: keyof ThreadExtendedData | (keyof ThreadExtendedData)[]) => ThreadExtendedData;
			readonly startupData: () => ThreadStartupData;
		};
		readonly threadCommands: {
			readonly create: (input: ThreadCreateData) => RepositoryResult<{
				id: EARS.EntityId;
				shortCode: string;
				timestamp: number;
			}>;
			readonly update: (id: EARS.EntityId, updates: {
				topic?: string;
				instructions?: string;
				status?: ThreadEntity["status"];
				tags?: ThreadTagItem[];
				linkedThreads?: any[];
			}) => OperationResult;
			readonly createTag: (name: string) => RepositoryResult<EARS.EntityId>;
		};
	};
};
declare const services: {
	logger: {
		source?: string;
		log(level: LogLevel, message: string, meta?: Record<string, any>): void;
		debug(message: string, meta?: Record<string, any>): void;
		info(message: string, meta?: Record<string, any>): void;
		warn(message: string, meta?: Record<string, any>): void;
		error(message: string, meta?: Record<string, any>): void;
	};
	llm: any;
	emitter: any;
	database: any;
	prompt: PromptService;
	action: ActionService;
	library: LibraryService;
	browser: any;
	repository: {
		readonly actionQueries: {
			readonly byId: (id: EARS.EntityId) => ActionEntity | undefined;
			readonly all: () => ActionEntity[];
			readonly byCategory: (category: string) => ActionEntity[];
			readonly paginated: (page?: number, pageSize?: number) => {
				items: ActionEntity[];
				page: number;
				pageSize: number;
				totalCount: number;
				totalPages: number;
			};
			readonly startupData: (page?: number) => {
				actions: ActionEntity[];
				page: number;
				totalPages: number;
				totalCount: number;
			};
		};
		readonly actionCommands: {
			readonly create: (data: {
				label: string;
				description?: string;
				category?: string;
				input?: Record<string, any>;
				actionFn: string;
				output?: any;
			}) => RepositoryResult<ActionEntity>;
			readonly update: (id: EARS.EntityId, updates: {
				label?: string;
				description?: string;
				category?: string;
				input?: Record<string, any>;
				actionFn?: string;
				output?: any;
			}) => OperationResult;
			readonly delete: (id: EARS.EntityId) => OperationResult;
		};
		readonly agentQueries: {
			readonly threadArtifacts: (threadId: EARS.EntityId) => {
				id: `Agent-${string}` | `Brain-${string}` | `Message-${string}` | `Thread-${string}` | `Tag-${string}` | `Relation-${string}` | `Artifact-${string}` | `Flow-${string}` | `Node-${string}` | `TNode-${string}` | `Prompt-${string}` | `Action-${string}` | `Document-${string}` | `Collection-${string}` | `SearchIndex-${string}` | `Terminal-${string}` | `Directory-${string}`;
				type: unknown;
				title: unknown;
				content: unknown;
			}[];
			readonly threadData: (threadId: EARS.EntityId) => AgentThreadData;
			readonly refreshThreadsData: () => RecentThreadRefreshData;
			readonly startupData: () => AgentStartupData;
		};
		readonly agentCommands: {
			readonly addMessage: (params: {
				threadId: EARS.EntityId;
				text: string;
				sender: "user" | "assistant" | "system";
			}) => RepositoryResult<{
				id: EARS.EntityId;
				threadId: EARS.EntityId;
				text: string;
				sender: string;
				timestamp: number;
			}>;
		};
		readonly brainQueries: {
			readonly rootFlowTNode: () => EARS.EntityId | undefined;
			readonly tNodeById: (id: EARS.EntityId) => TNodeEntity | null;
			readonly flowEventNodes: (flowId: EARS.EntityId) => ListenNode[];
			readonly eventFirstStep: (eventNodeId: EARS.EntityId) => NodeEntity | undefined;
			readonly nextNodeInFlowTrack: (nodeId: EARS.EntityId) => NodeEntity;
			readonly eventTracks: (flowTNodeId: EARS.EntityId) => TrackEntity[];
			readonly possibleEvents: (flowTNodeId: EARS.EntityId) => EventListenerEntity[];
			readonly extendedTNodeData: (tNodeId: EARS.EntityId) => FlowTNodeData;
			readonly rootData: () => FlowTNodeData;
		};
		readonly brainCommands: {
			readonly createEventTNode: (eventNode: ListenNode, flowTNodeId: EARS.EntityId) => TNodeEntity;
			readonly createFlowTNode: (flowStepId: EARS.EntityId, eventTrackId?: EARS.EntityId, executionContext?: ExecutionContext) => {
				flowTNode: TNodeEntity;
				eventNodes: ListenNode[];
			};
			readonly createStepTNode: (stepId: EARS.EntityId, eventTrackId: EARS.EntityId, executionContext?: ExecutionContext) => {
				tNode: TNodeEntity;
				step: NodeEntity;
			};
			readonly createRootFlowTNode: () => {
				rootFlow: FlowEntity;
				rootFlowTNode: TNodeEntity;
				eventNodes: ListenNode[];
				entryNode: ListenNode;
			};
			readonly updateTNodeStatus: (tNodeId: EARS.EntityId, status: TNodeEntity["status"]) => void;
			readonly updateTNodeResult: (tNodeId: EARS.EntityId, result: any) => void;
			readonly updateTNodeAttributes: (tNodeId: EARS.EntityId, attributes: any) => void;
		};
		readonly flowsQueries: {
			readonly rootFlow: () => EARS.EntityId | undefined;
			readonly getNodeActionId: (nodeId: EARS.EntityId) => EARS.EntityId | undefined;
			readonly node: (nodeId: EARS.EntityId) => NodeEntity | undefined;
			readonly flowNodes: (flowId: EARS.EntityId) => NodeEntity[];
			readonly flowEdges: (flowId: EARS.EntityId) => EdgeEntity[];
			readonly extendedData: (flowId: EARS.EntityId, include?: keyof FlowExtendedData | (keyof FlowExtendedData)[]) => FlowExtendedData;
			readonly startupData: () => FlowsStartupData;
		};
		readonly flowsCommands: {
			readonly createFlow: (flow?: Partial<FlowEntity>) => RepositoryResult<FlowEntity>;
			readonly createFlowWithEntryNode: (flow?: Partial<FlowEntity>) => RepositoryResult<{
				flow: FlowEntity;
				entryNode: NodeEntity;
			}>;
			readonly createNode: (flowId: EARS.EntityId, nodeData: NodeCreateInput) => RepositoryResult<NodeEntity>;
			readonly createEdge: (sourceId: EARS.EntityId, targetId: EARS.EntityId) => RepositoryResult<{
				relId: EARS.EntityId;
			}>;
			readonly updateFlowLabel: (flowId: EARS.EntityId, label: string) => OperationResult;
			readonly updateNode: (nodeId: EARS.EntityId, updates: NodeCreateInput) => OperationResult;
			readonly deleteNode: (nodeId: EARS.EntityId) => OperationResult;
			readonly deleteEdge: (edgeId: EARS.EntityId) => OperationResult;
			readonly updateEdge: (edgeId: EARS.EntityId, oldSource: EARS.EntityId, oldTarget: EARS.EntityId, newSource: EARS.EntityId, newTarget: EARS.EntityId) => RepositoryResult<{
				newRelId: EARS.EntityId;
			}>;
		};
		readonly libraryQueries: {
			readonly getDocuments: (collectionId?: string) => DocumentDTO[];
			readonly getDocument: (id: EARS.EntityId) => DocumentDTO | null;
			readonly getDocumentByShortCode: (shortCode: DocumentShortCode) => DocumentDTO | null;
			readonly getCollections: () => CollectionDTO[];
			readonly getFolderContents: (folderId: EARS.EntityId | null) => FolderContents;
			readonly getFolderPath: (folderId: EARS.EntityId | null) => BreadcrumbItem[];
			readonly getParentFolderId: (folderId: EARS.EntityId) => EARS.EntityId | null;
			readonly getCollectionByName: (name: string) => CollectionDTO | null;
			readonly getDocumentsInCollection: (collectionId: EARS.EntityId) => DocumentDTO[];
		};
		readonly libraryCommands: {
			readonly createDocument: (name: string, content: ContentSection[], tags: string[], collectionId?: EARS.EntityId) => DocumentDTO;
			readonly updateDocument: (id: EARS.EntityId, name: string, content: ContentSection[], tags: string[], collectionId?: EARS.EntityId) => DocumentDTO;
			readonly deleteDocument: (id: EARS.EntityId) => void;
			readonly createCollection: (name: string, description?: string, parentId?: EARS.EntityId) => CollectionDTO;
			readonly updateCollection: (id: EARS.EntityId, name: string, description?: string) => CollectionDTO;
			readonly deleteCollection: (id: EARS.EntityId) => void;
			readonly moveDocument: (documentId: EARS.EntityId, newCollectionId?: EARS.EntityId) => DocumentDTO;
			readonly renameItem: (id: EARS.EntityId, name: string, type: "document" | "folder") => LibraryItem;
			readonly deleteItems: (ids: EARS.EntityId[]) => void;
			readonly moveItems: (ids: EARS.EntityId[], targetFolderId: EARS.EntityId | null) => void;
			readonly reorderItems: (itemIds: EARS.EntityId[], targetIndex: number, targetFolderId: EARS.EntityId | null) => void;
			readonly migrateDocumentShortCodes: () => void;
			readonly migrateDisplayOrders: () => void;
		};
		readonly promptQueries: {
			byId: (id: EARS.EntityId) => PromptEntity | undefined;
			all: () => PromptEntity[];
			byLabel: (label: string) => PromptEntity | undefined;
			startupData: (page?: number, pageSize?: number) => {
				prompts: PromptEntity[];
				page: number;
				totalPages: number;
				totalCount: number;
			};
		};
		readonly promptCommands: {
			create: (input: {
				label: string;
				description?: string;
				templateFn: string;
				inputs?: Record<string, any>;
			}) => RepositoryResult<PromptEntity>;
			update: (id: EARS.EntityId, updates: {
				label?: string;
				description?: string;
				templateFn?: string;
				inputs?: Record<string, any>;
			}) => OperationResult;
			delete: (id: EARS.EntityId) => OperationResult;
		};
		readonly terminalQueries: {
			byId: (id: EARS.EntityId) => TerminalEntity | undefined;
			all: () => TerminalEntity[];
			active: () => TerminalEntity[];
			getStartupData: () => StartupData;
		};
		readonly terminalCommands: {
			create: (terminalInfo: Partial<TerminalInfo> & {
				id: EARS.EntityId;
			}) => EARS.EntityId;
			resize: (id: EARS.EntityId, cols: number, rows: number) => void;
			updatePid: (id: EARS.EntityId, pid: number) => void;
			markClosed: (id: EARS.EntityId) => void;
			delete: (id: EARS.EntityId) => void;
		};
		readonly directoryQueries: {
			getLastOpenedDirectory: () => DirectoryEntity | undefined;
			getRecentDirectories: (limit?: number) => DirectoryEntity[];
			findByPath: (path: string) => DirectoryEntity | undefined;
		};
		readonly directoryCommands: {
			saveDirectory: (path: string, label?: string) => EARS.EntityId;
			markAsLastOpened: (path: string) => void;
			clearAll: () => void;
		};
		readonly threadQueries: {
			readonly byId: (id: EARS.EntityId) => ThreadEntity | undefined;
			readonly all: () => ThreadEntity[];
			readonly allByRecency: () => ThreadEntity[];
			readonly messages: (threadId: EARS.EntityId) => Partial<MessageEntity>[];
			readonly tags: (threadId: EARS.EntityId) => ThreadTagItem[];
			readonly linkedThreads: (threadId: EARS.EntityId) => any[];
			readonly extendedData: (threadId: EARS.EntityId, include?: keyof ThreadExtendedData | (keyof ThreadExtendedData)[]) => ThreadExtendedData;
			readonly startupData: () => ThreadStartupData;
		};
		readonly threadCommands: {
			readonly create: (input: ThreadCreateData) => RepositoryResult<{
				id: EARS.EntityId;
				shortCode: string;
				timestamp: number;
			}>;
			readonly update: (id: EARS.EntityId, updates: {
				topic?: string;
				instructions?: string;
				status?: ThreadEntity["status"];
				tags?: ThreadTagItem[];
				linkedThreads?: any[];
			}) => OperationResult;
			readonly createTag: (name: string) => RepositoryResult<EARS.EntityId>;
		};
	};
};
interface ActionParams {
	[key: string]: any;
}
type Services = typeof services;
declare global {
	const params: ActionParams;
	const services: typeof services;
	const z: any;
}

declare namespace browser {
	export { Browser, BrowserContext, BrowserService, LaunchOptions, Page, chromium, createBrowser, firefox, webkit };
}

export as namespace ActionDSL;
